/* AUTO-GENERATED by tools/match_news.py — do not edit by hand. */
window.NEWS_ITEMS = [
  {id:"2026-09-04_bank-abc-receives-best-bank-for-cash-man_311a95", date:"2026-09-04", title:"Bank ABC receives Best Bank for Cash Management award", source:"GDN", url:"https://www.gdnonline.com/Details/1405194/Bank-ABC-receives-Best-Bank-for-Cash-Management-award", ids:["abc"]},
  {id:"2026-09-03_alba-boosts-bahrainisation-with-two-key-_5684d9", date:"2026-09-03", title:"Alba boosts Bahrainisation with two key management promotions", source:"TradeArabia", url:"http://www.tradearabia.com/News/466623/Alba-boosts-Bahrainisation-with-two-key-management-promotions", ids:["alba"]},
  {id:"2026-09-03_hrh-the-crown-prince-prime-minister-and-_da25a0", date:"2026-09-03", title:"HRH the Crown Prince, Prime Minister and Chairman of the Bahrain EDB issues Edict (2) of 2026", source:"BNA", url:"https://www.bna.bh/en/HRHtheCrownPrincePrimeMinisterandChairmanoftheBahrainEDBissuesEdict2of2026.aspx?cms=q8FmFJgiscL2fwIzON1%2bDicoqLxHNNVjWNXS%2bdhrZ9k%3d", ids:["edb"]},
  {id:"2026-09-03_national-bank-of-bahrain-names-new-equal_be0ebc", date:"2026-09-03", title:"National Bank of Bahrain names new equal opportunities committee", source:"TradeArabia", url:"http://www.tradearabia.com/News/466587/National-Bank-of-Bahrain-names-new-equal-opportunities-committee", ids:["nbb"]},
];
window.SUGGESTED_EDGES = [];
