/* AUTO-GENERATED by tools/match_news.py — do not edit by hand.
   Re-run the script after adding files to news_inbox/. */
window.NEWS_ITEMS = [
  {id:"2026-08-22_sample-adnoc-taqa", date:"2026-08-22", title:"[SAMPLE] ADNOC and TAQA weigh joint clean-power supply for offshore fields", source:"SAMPLE — replace with real news", url:"", ids:["adnoc","awaidha_marar","doe","ewec","jasim_thabet","masdar","taqa"]},
  {id:"2026-08-20_sample-g42-microsoft", date:"2026-08-20", title:"[SAMPLE] Microsoft and G42 expand Abu Dhabi AI datacenter build-out", source:"SAMPLE — replace with real news", url:"", ids:["g42","khazna","mgx","microsoft","peng_xiao","sultan_jaber"]},
];
