/* AUTO-GENERATED by tools/match_news.py — do not edit by hand. */
window.NEWS_ITEMS = [
  {id:"2026-09-03_standard-chartered-brings-crypto-spot-tr_04d6fb", date:"2026-09-03", title:"Standard Chartered brings crypto spot trading to UAE", source:"AGBI", url:"https://www.agbi.com/banking-finance/2026/09/standard-chartered-brings-crypto-spot-trading-to-uae/", ids:["difc"]},
  {id:"2026-09-03_uae-flights-latest-emirates-and-etihad-d_852752", date:"2026-09-03", title:"UAE flights latest: Emirates and Etihad delays and cancellations as US-Iran tensions continue", source:"Arabian Business", url:"https://www.arabianbusiness.com/business/transport/uae-flights-update", ids:["emirates"]},
  {id:"2026-09-03_emirates-flies-specialist-dogs-into-anti_a2d340", date:"2026-09-03", title:"Emirates flies specialist dogs into anti-poaching role2m read", source:"Gulf News", url:"https://gulfnews.com/business/aviation/emirates-flown-k9-unit-begins-anti-poaching-operations-in-zimbabwe-1.500661722", ids:["emirates"]},
  {id:"2026-09-03_emirates-unveils-electric-premium-econom_9687dd", date:"2026-09-03", title:"Emirates unveils electric Premium Economy seats 1h ago2m read", source:"Gulf News", url:"https://gulfnews.com/business/aviation/emirates-unveils-one-of-its-kind-electric-premium-economy-seats-1.500662175", ids:["emirates"]},
  {id:"2026-09-03_emirates-unveils-world-s-first-electric-_e06504", date:"2026-09-03", title:"Emirates unveils world's first electric premium economy seat with privacy screen", source:"The National", url:"https://www.thenationalnews.com/travel/2026/09/03/emirates-electric-premium-economy-seats-headrest-privacy-screen/", ids:["emirates"]},
];
window.SUGGESTED_EDGES = [];
