/* AUTO-GENERATED by tools/match_news.py — do not edit by hand. */
window.NEWS_ITEMS = [
  {id:"2026-09-03_uae-flights-latest-emirates-and-etihad-d_852752", date:"2026-09-03", title:"UAE flights latest: Emirates and Etihad delays and cancellations as US-Iran tensions continue", source:"Arabian Business", url:"https://www.arabianbusiness.com/business/transport/uae-flights-update", ids:["emirates"]},
  {id:"2026-09-03_emirates-flies-specialist-dogs-into-anti_a2d340", date:"2026-09-03", title:"Emirates flies specialist dogs into anti-poaching role2m read", source:"Gulf News", url:"https://gulfnews.com/business/aviation/emirates-flown-k9-unit-begins-anti-poaching-operations-in-zimbabwe-1.500661722", ids:["emirates"]},
];
window.SUGGESTED_EDGES = [];
