/* AUTO-GENERATED by tools/match_news.py — do not edit by hand. */
window.NEWS_ITEMS = [
  {id:"2026-09-03_uae-flights-latest-emirates-and-etihad-d_852752", date:"2026-09-03", title:"UAE flights latest: Emirates and Etihad delays and cancellations as US-Iran tensions continue", source:"Arabian Business", url:"https://www.arabianbusiness.com/business/transport/uae-flights-update", ids:["lst_emirates"]},
];
window.SUGGESTED_EDGES = [];
