/* ================================================================
   SAUDI ARABIA POWER NETWORK — DATASET (V1 backbone)
   Tiers: 0 ruling core · 1 state & capital · 2 operators · 3 private/intl.
   "v" established public fact · "ns" needs source check.
   ================================================================ */

const SECTORS = {
  // ---- GICS 11 ----
  energy:       {name:"Energy",                 color:"#f2703e"},
  materials:    {name:"Materials",              color:"#b08968"},
  industry:     {name:"Industrials",            color:"#c98a5e"},
  consumer_disc:{name:"Consumer Discretionary", color:"#ef7fb1"},
  consumer_stap:{name:"Consumer Staples",       color:"#9ccc65"},
  health:       {name:"Health Care",            color:"#35b8a4"},
  finance:      {name:"Financials",             color:"#3ecf8e"},
  tech:         {name:"Information Technology", color:"#a06ef5"},
  comm:         {name:"Communication Services", color:"#7e57c2"},
  utilities:    {name:"Utilities",              color:"#f5a623"},
  realestate:   {name:"Real Estate",            color:"#58c4dd"},
  // ---- government-side sectors (a power map needs these) ----
  gov:          {name:"Government & Political", color:"#5b8def"},
  sovereign:    {name:"Sovereign Capital",      color:"#e8b64c"},
  education:    {name:"Education & Research",   color:"#8bc34a"},
  conglomerate: {name:"Family Conglomerates",   color:"#b0a08a"},
};

const INSTITUTIONS = [
  {id:"royalcourt", n:"Royal Court (Al Saud)",       s:"gov", t:0, p:100, short:"Royal Court"},
  {id:"com",       n:"Council of Ministers",         s:"gov", t:0, p:92,  short:"Cabinet"},
  {id:"mof_sa",    n:"Ministry of Finance",          s:"gov", t:1, p:86,  short:"MoF"},
  {id:"mofa_sa",   n:"Ministry of Foreign Affairs",  s:"gov", t:1, p:86,  short:"MoFA"},
  {id:"mod_sa",    n:"Ministry of Defense",          s:"gov", t:1, p:88,  short:"MoD"},
  {id:"moenergy",  n:"Ministry of Energy",           s:"energy", t:1, p:90, short:"Min. Energy"},
  {id:"misa",      n:"Ministry of Investment",       s:"gov", t:1, p:82,  short:"MISA"},
  {id:"mcit_sa",   n:"Ministry of Communications & IT", s:"tech", t:1, p:78, short:"MCIT"},
  {id:"moc_sa",    n:"Ministry of Commerce",         s:"gov", t:1, p:74,  short:"Min. Commerce"},
  {id:"moind",     n:"Ministry of Industry & Mineral Resources", s:"gov", t:1, p:74, short:"Min. Industry"},
  {id:"mot_sa",    n:"Ministry of Tourism",          s:"gov", t:1, p:74, short:"Min. Tourism"},
  {id:"sama",      n:"Saudi Central Bank (SAMA)",    s:"finance", t:1, p:84, short:"SAMA"},
  {id:"sdaia",     n:"SDAIA (Data & AI Authority)",  s:"tech", t:1, p:74,  short:"SDAIA"},
  {id:"gea",       n:"General Entertainment Authority", s:"gov", t:1, p:74, short:"GEA"},
  {id:"pif",       n:"Public Investment Fund",       s:"sovereign", t:1, p:97, short:"PIF"},
  {id:"aramco",    n:"Saudi Aramco",                 s:"energy", t:1, p:96, short:"Aramco"},
  {id:"sabic",     n:"SABIC",                        s:"materials", t:1, p:80, short:"SABIC"},
  {id:"maaden",    n:"Ma'aden",                      s:"materials", t:2, p:76, short:"Ma'aden"},
  {id:"stc",       n:"stc Group",                    s:"comm", t:1, p:78, short:"stc"},
  {id:"sec",       n:"Saudi Electricity Company",    s:"utilities", t:2, p:70, short:"SEC"},
  {id:"acwa",      n:"ACWA Power",                   s:"utilities", t:1, p:78, short:"ACWA Power"},
  {id:"snb",       n:"Saudi National Bank",          s:"finance", t:1, p:78, short:"SNB"},
  {id:"alrajhi",   n:"Al Rajhi Bank",                s:"finance", t:1, p:78, short:"Al Rajhi"},
  {id:"sab",       n:"Saudi Awwal Bank",             s:"finance", t:2, p:66, short:"SAB"},
  {id:"tadawul",   n:"Saudi Exchange (Tadawul)",     s:"finance", t:2, p:70, short:"Tadawul"},
  {id:"neom",      n:"NEOM",                         s:"realestate", t:1, p:80, short:"NEOM"},
  {id:"redsea",    n:"Red Sea Global",               s:"realestate", t:2, p:70, short:"Red Sea Global"},
  {id:"qiddiya",   n:"Qiddiya",                      s:"consumer_disc", t:2, p:66, short:"Qiddiya"},
  {id:"diriyah",   n:"Diriyah Company",              s:"consumer_disc", t:2, p:70, short:"Diriyah"},
  {id:"roshn",     n:"ROSHN",                        s:"realestate", t:2, p:68, short:"ROSHN"},
  {id:"humain",    n:"HUMAIN (PIF AI company)",      s:"tech", t:2, p:72, short:"HUMAIN"},
  {id:"alat",      n:"Alat",                         s:"tech", t:2, p:70, short:"Alat"},
  {id:"saudia",    n:"Saudia",                       s:"industry", t:2, p:70, short:"Saudia"},
  {id:"riyadhair", n:"Riyadh Air",                   s:"industry", t:2, p:72, short:"Riyadh Air"},
  {id:"sami",      n:"SAMI (Saudi Arabian Military Industries)", s:"industry", t:2, p:70, short:"SAMI"},
  {id:"srmg",      n:"SRMG",                         s:"comm", t:2, p:64, short:"SRMG"},
  {id:"mbcgroup",  n:"MBC Group",                    s:"comm", t:2, p:68, short:"MBC"},
  {id:"almarai",   n:"Almarai",                      s:"consumer_stap", t:2, p:66, short:"Almarai"},
  {id:"habib",     n:"Dr. Sulaiman Al Habib Medical Group", s:"health", t:2, p:70, short:"Al Habib Medical"},
  {id:"kingdomholding", n:"Kingdom Holding",         s:"conglomerate", t:3, p:72, short:"Kingdom Holding"},
  {id:"olayan",    n:"Olayan Group",                 s:"conglomerate", t:3, p:70, short:"Olayan"},
  {id:"alfaisaliah", n:"Al Faisaliah Group",         s:"conglomerate", t:3, p:60, short:"Al Faisaliah"},
  {id:"ajlan",     n:"Ajlan & Bros",                 s:"conglomerate", t:3, p:62, short:"Ajlan & Bros"},
  {id:"lst_2030", n:"Saudi Arabia Refineries Co.", s:"energy", t:2, p:50, short:"2030"},
  {id:"lst_2380", n:"Rabigh Refining and Petrochemical Co. (Petro Rabigh)", s:"energy", t:2, p:50, short:"2380"},
  {id:"lst_4030", n:"National Shipping Co. of Saudi Arabia (Bahri)", s:"energy", t:2, p:50, short:"4030"},
  {id:"lst_2381", n:"Arabian Drilling Co.", s:"energy", t:2, p:50, short:"Arabian Drilling Co."},
  {id:"lst_2382", n:"ADES Holding Co.", s:"energy", t:2, p:50, short:"ADES Holding Co."},
  {id:"lst_1201", n:"Takween Advanced Industries Co.", s:"materials", t:2, p:50, short:"1201"},
  {id:"lst_1202", n:"Middle East Paper Co. (Mepco)", s:"materials", t:2, p:50, short:"1202"},
  {id:"lst_1210", n:"Basic Chemical Industries Co. (BCI)", s:"materials", t:2, p:50, short:"1210"},
  {id:"lst_1301", n:"Aslak Co.", s:"materials", t:2, p:50, short:"Aslak Co."},
  {id:"lst_1304", n:"Al Yamamah Steel Industries Co.", s:"materials", t:2, p:50, short:"1304"},
  {id:"lst_1320", n:"Saudi Steel Pipe Co.", s:"materials", t:2, p:50, short:"Saudi Steel Pipe Co."},
  {id:"lst_2001", n:"Chemanol (National Methanol Co.)", s:"materials", t:2, p:50, short:"2001"},
  {id:"lst_2090", n:"National Gas and Industrialization Co.", s:"materials", t:2, p:50, short:"2090"},
  {id:"lst_2150", n:"Zoujaj Industrial Co.", s:"materials", t:2, p:50, short:"2150"},
  {id:"lst_2170", n:"Alujain Corp.", s:"materials", t:2, p:50, short:"Alujain Corp."},
  {id:"lst_2180", n:"Filling and Packing Materials Manufacturing Co. (FIPCO)", s:"materials", t:2, p:50, short:"2180"},
  {id:"lst_2200", n:"Arabian Pipes Co.", s:"materials", t:2, p:50, short:"Arabian Pipes Co."},
  {id:"lst_2210", n:"Nama Chemicals Co.", s:"materials", t:2, p:50, short:"Nama Chemicals Co."},
  {id:"lst_2220", n:"National Metal Manufacturing and Casting Co. (Maadaniyah)", s:"materials", t:2, p:50, short:"2220"},
  {id:"lst_2240", n:"Zamil Industrial Investment Co.", s:"materials", t:2, p:50, short:"2240"},
  {id:"lst_2250", n:"Saudi Industrial Investment Group", s:"materials", t:2, p:50, short:"2250"},
  {id:"lst_2290", n:"Yanbu National Petrochemical Co. (Yansab)", s:"materials", t:2, p:50, short:"2290"},
  {id:"lst_2300", n:"Saudi Paper Manufacturing Co.", s:"materials", t:2, p:50, short:"2300"},
  {id:"lst_2310", n:"Sahara International Petrochemical Co. (Sipchem)", s:"materials", t:2, p:50, short:"2310"},
  {id:"lst_2330", n:"Advanced Petrochemical Co.", s:"materials", t:2, p:50, short:"2330"},
  {id:"lst_2350", n:"Saudi Kayan Petrochemical Co.", s:"materials", t:2, p:50, short:"2350"},
  {id:"lst_2360", n:"Saudi Vitrified Clay Pipes Co.", s:"materials", t:2, p:50, short:"2360"},
  {id:"lst_3002", n:"Najran Cement Co.", s:"materials", t:2, p:50, short:"Najran Cement Co."},
  {id:"lst_3003", n:"City Cement Co.", s:"materials", t:2, p:50, short:"City Cement Co."},
  {id:"lst_3004", n:"Northern Region Cement Co.", s:"materials", t:2, p:50, short:"3004"},
  {id:"lst_3005", n:"United Arab Cement Co.", s:"materials", t:2, p:50, short:"3005"},
  {id:"lst_3007", n:"Oasis Trading and Marketing Co.", s:"materials", t:2, p:50, short:"3007"},
  {id:"lst_3008", n:"Al Kathiri Holding Co.", s:"materials", t:2, p:50, short:"3008"},
  {id:"lst_3010", n:"Arabian Cement Co.", s:"materials", t:2, p:50, short:"Arabian Cement Co."},
  {id:"lst_3020", n:"Yamama Cement Co.", s:"materials", t:2, p:50, short:"Yamama Cement Co."},
  {id:"lst_3030", n:"Saudi Cement Co.", s:"materials", t:2, p:50, short:"Saudi Cement Co."},
  {id:"lst_3040", n:"Qassim Cement Co.", s:"materials", t:2, p:50, short:"Qassim Cement Co."},
  {id:"lst_3050", n:"Southern Province Cement Co.", s:"materials", t:2, p:50, short:"3050"},
  {id:"lst_3060", n:"Yanbu Cement Co.", s:"materials", t:2, p:50, short:"Yanbu Cement Co."},
  {id:"lst_3080", n:"Eastern Province Cement Co.", s:"materials", t:2, p:50, short:"3080"},
  {id:"lst_3090", n:"Tabuk Cement Co.", s:"materials", t:2, p:50, short:"Tabuk Cement Co."},
  {id:"lst_3091", n:"Jouf Cement Co.", s:"materials", t:2, p:50, short:"Jouf Cement Co."},
  {id:"lst_3092", n:"Riyadh Cement Co.", s:"materials", t:2, p:50, short:"Riyadh Cement Co."},
  {id:"lst_2060", n:"National Industrialization Co. (Tasnee)", s:"materials", t:2, p:50, short:"2060"},
  {id:"lst_1321", n:"East Pipes Integrated Co.", s:"materials", t:2, p:50, short:"1321"},
  {id:"lst_1322", n:"Amak International Holding Co.", s:"materials", t:2, p:50, short:"1322"},
  {id:"lst_1323", n:"United Carton Industries Co.", s:"materials", t:2, p:50, short:"1323"},
  {id:"lst_1324", n:"Saleh Abdulaziz Al Rashed and Sons Co.", s:"materials", t:2, p:50, short:"1324"},
  {id:"lst_1212", n:"Astra Industrial Group", s:"industry", t:2, p:50, short:"1212"},
  {id:"lst_1302", n:"Bawan Co.", s:"industry", t:2, p:50, short:"Bawan Co."},
  {id:"lst_1303", n:"Electrical Industries Co.", s:"industry", t:2, p:50, short:"1303"},
  {id:"lst_1214", n:"Shaker Group", s:"industry", t:2, p:50, short:"Shaker Group"},
  {id:"lst_2040", n:"Saudi Ceramics Co.", s:"industry", t:2, p:50, short:"Saudi Ceramics Co."},
  {id:"lst_2110", n:"Saudi Cable Co.", s:"industry", t:2, p:50, short:"Saudi Cable Co."},
  {id:"lst_2160", n:"Amiantit (Saudi Arabian Amiantit Co.)", s:"industry", t:2, p:50, short:"2160"},
  {id:"lst_2320", n:"Al Babtain Power and Telecommunication Co.", s:"industry", t:2, p:50, short:"2320"},
  {id:"lst_2370", n:"Middle East Specialized Cables Co. (MESC)", s:"industry", t:2, p:50, short:"2370"},
  {id:"lst_4110", n:"Batic Investments and Logistics Co.", s:"industry", t:2, p:50, short:"4110"},
  {id:"lst_4140", n:"Saudi Industrial Export Co. (SIECO)", s:"industry", t:2, p:50, short:"4140"},
  {id:"lst_4141", n:"Al Omran Industrial Trading Co.", s:"industry", t:2, p:50, short:"4141"},
  {id:"lst_4142", n:"Riyadh Cables Group Co.", s:"industry", t:2, p:50, short:"4142"},
  {id:"lst_4144", n:"Raoom Trading Co.", s:"industry", t:2, p:50, short:"Raoom Trading Co."},
  {id:"lst_4145", n:"Obeikan Glass Co. (OGC)", s:"industry", t:2, p:50, short:"4145"},
  {id:"lst_4146", n:"Gulf Applied Solutions Co. (Gas Arabian Services)", s:"industry", t:2, p:50, short:"4146"},
  {id:"lst_4147", n:"Canar Telecommunication Co.", s:"industry", t:2, p:50, short:"4147"},
  {id:"lst_4148", n:"Alwasail Industrial Co.", s:"industry", t:2, p:50, short:"4148"},
  {id:"lst_1831", n:"Maharah Human Resources Co.", s:"industry", t:2, p:50, short:"1831"},
  {id:"lst_1832", n:"Saudi Distribution and Logistics Co. (SADR)", s:"industry", t:2, p:50, short:"1832"},
  {id:"lst_1833", n:"Al Mawarid Manpower Co.", s:"industry", t:2, p:50, short:"1833"},
  {id:"lst_1834", n:"Saudi Manpower Solutions Co. (SMASCO)", s:"industry", t:2, p:50, short:"1834"},
  {id:"lst_1835", n:"Tamkeen Human Resources Co.", s:"industry", t:2, p:50, short:"1835"},
  {id:"lst_4270", n:"Saudi Printing and Packaging Co. (SPPC)", s:"industry", t:2, p:50, short:"4270"},
  {id:"lst_6004", n:"Catrion Catering Holding Co.", s:"industry", t:2, p:50, short:"6004"},
  {id:"lst_2190", n:"Saudi Industrial Services Co. (SISCO Holding)", s:"industry", t:2, p:50, short:"2190"},
  {id:"lst_4031", n:"Saudi Ground Services Co.", s:"industry", t:2, p:50, short:"4031"},
  {id:"lst_4040", n:"Saudi Public Transport Co. (SAPTCO)", s:"industry", t:2, p:50, short:"4040"},
  {id:"lst_4260", n:"Budget Saudi Rent a Car Co.", s:"industry", t:2, p:50, short:"4260"},
  {id:"lst_4261", n:"Theeb Rent a Car Co.", s:"industry", t:2, p:50, short:"Theeb Rent a Car Co."},
  {id:"lst_4262", n:"Lumi Rental Co.", s:"industry", t:2, p:50, short:"Lumi Rental Co."},
  {id:"lst_4263", n:"SAL Saudi Logistics Services Co.", s:"industry", t:2, p:50, short:"4263"},
  {id:"lst_4264", n:"flynas Co.", s:"industry", t:2, p:50, short:"flynas Co."},
  {id:"lst_4265", n:"Cherry Trading Co.", s:"industry", t:2, p:50, short:"Cherry Trading Co."},
  {id:"lst_1213", n:"Naseej International Trading Co.", s:"consumer_disc", t:2, p:50, short:"1213"},
  {id:"lst_2130", n:"Saudi Industrial Development Co. (SIDC)", s:"consumer_disc", t:2, p:50, short:"2130"},
  {id:"lst_2340", n:"Artex Industrial Investment Co.", s:"consumer_disc", t:2, p:50, short:"2340"},
  {id:"lst_4011", n:"Lazurde Co. for Jewelry", s:"consumer_disc", t:2, p:50, short:"4011"},
  {id:"lst_4012", n:"Al Aseel Co.", s:"consumer_disc", t:2, p:50, short:"Al Aseel Co."},
  {id:"lst_4180", n:"Fitaihi Holding Group", s:"consumer_disc", t:2, p:50, short:"4180"},
  {id:"lst_1810", n:"Seera Group Holding", s:"consumer_disc", t:2, p:50, short:"Seera Group Holding"},
  {id:"lst_1820", n:"Baan Holding Group Co.", s:"consumer_disc", t:2, p:50, short:"1820"},
  {id:"lst_1830", n:"Leejam Sports Co.", s:"consumer_disc", t:2, p:50, short:"Leejam Sports Co."},
  {id:"lst_4170", n:"Emaar The Economic City Trading Co. (TECO)", s:"consumer_disc", t:2, p:50, short:"4170"},
  {id:"lst_4290", n:"Alkhaleej Training and Education Co.", s:"consumer_disc", t:2, p:50, short:"4290"},
  {id:"lst_4291", n:"National Company for Learning and Education (NCLE)", s:"consumer_disc", t:2, p:50, short:"4291"},
  {id:"lst_4292", n:"Ataa Educational Co.", s:"consumer_disc", t:2, p:50, short:"Ataa Educational Co."},
  {id:"lst_6002", n:"Herfy Food Services Co.", s:"consumer_disc", t:2, p:50, short:"6002"},
  {id:"lst_6012", n:"Raydan Food Co.", s:"consumer_disc", t:2, p:50, short:"Raydan Food Co."},
  {id:"lst_6013", n:"Development Works Food Co.", s:"consumer_disc", t:2, p:50, short:"6013"},
  {id:"lst_6014", n:"Alamar Foods Co.", s:"consumer_disc", t:2, p:50, short:"Alamar Foods Co."},
  {id:"lst_6015", n:"Americana Restaurants International", s:"consumer_disc", t:2, p:50, short:"6015"},
  {id:"lst_6016", n:"Burgerizzr Co.", s:"consumer_disc", t:2, p:50, short:"Burgerizzr Co."},
  {id:"lst_6017", n:"Jahez International Co.", s:"consumer_disc", t:2, p:50, short:"6017"},
  {id:"lst_6018", n:"Sport Clubs Co.", s:"consumer_disc", t:2, p:50, short:"Sport Clubs Co."},
  {id:"lst_6019", n:"Almasar Alshamil Education Co.", s:"consumer_disc", t:2, p:50, short:"6019"},
  {id:"lst_6022", n:"Armah Sports Co.", s:"consumer_disc", t:2, p:50, short:"Armah Sports Co."},
  {id:"lst_4070", n:"Arriyadh Development Co. (TAPRCO)", s:"comm", t:2, p:50, short:"4070"},
  {id:"lst_4071", n:"Saudi Research and Media Group Alarabia", s:"comm", t:2, p:50, short:"4071"},
  {id:"lst_4072", n:"MBC Group", s:"comm", t:2, p:50, short:"MBC Group"},
  {id:"lst_4003", n:"United Electronics Co. (eXtra)", s:"consumer_disc", t:2, p:50, short:"4003"},
  {id:"lst_4008", n:"Saudi Co. for Hardware (SACO)", s:"consumer_disc", t:2, p:50, short:"4008"},
  {id:"lst_4050", n:"Saudi Automotive Services Co. (SASCO)", s:"consumer_disc", t:2, p:50, short:"4050"},
  {id:"lst_4051", n:"Baazeem Trading Co.", s:"consumer_disc", t:2, p:50, short:"Baazeem Trading Co."},
  {id:"lst_4190", n:"Jarir Marketing Co.", s:"consumer_disc", t:2, p:50, short:"Jarir Marketing Co."},
  {id:"lst_4191", n:"Abo Moati Bookstores Co.", s:"consumer_disc", t:2, p:50, short:"4191"},
  {id:"lst_4192", n:"Alsaif Gallery Co.", s:"consumer_disc", t:2, p:50, short:"Alsaif Gallery Co."},
  {id:"lst_4193", n:"Nice One Beauty Digital Marketing Co.", s:"consumer_disc", t:2, p:50, short:"4193"},
  {id:"lst_4194", n:"Build Station Trading Co.", s:"consumer_disc", t:2, p:50, short:"4194"},
  {id:"lst_4200", n:"Aldrees Petroleum and Transport Services Co.", s:"consumer_disc", t:2, p:50, short:"4200"},
  {id:"lst_4240", n:"Cenomi Retail (Fawaz Abdulaziz Alhokair Co.)", s:"consumer_disc", t:2, p:50, short:"4240"},
  {id:"lst_4001", n:"Abdullah Al Othaim Markets Co.", s:"consumer_stap", t:2, p:50, short:"4001"},
  {id:"lst_4006", n:"Farm Superstores Co.", s:"consumer_stap", t:2, p:50, short:"Farm Superstores Co."},
  {id:"lst_4061", n:"Anaam International Holding Group", s:"consumer_stap", t:2, p:50, short:"4061"},
  {id:"lst_4160", n:"Thimar Development Holding Co.", s:"consumer_stap", t:2, p:50, short:"4160"},
  {id:"lst_4161", n:"Bindawood Holding Co.", s:"consumer_stap", t:2, p:50, short:"4161"},
  {id:"lst_4162", n:"Almunajem Foods Co.", s:"consumer_stap", t:2, p:50, short:"Almunajem Foods Co."},
  {id:"lst_4163", n:"Aldawaa Medical Services Co.", s:"consumer_stap", t:2, p:50, short:"4163"},
  {id:"lst_4164", n:"Nahdi Medical Co.", s:"consumer_stap", t:2, p:50, short:"Nahdi Medical Co."},
  {id:"lst_2050", n:"Savola Group", s:"consumer_stap", t:2, p:50, short:"Savola Group"},
  {id:"lst_2100", n:"Wafrah for Industry and Development Co.", s:"consumer_stap", t:2, p:50, short:"2100"},
  {id:"lst_2281", n:"Tanmiah Food Co.", s:"consumer_stap", t:2, p:50, short:"Tanmiah Food Co."},
  {id:"lst_2282", n:"Naqi Water Co.", s:"consumer_stap", t:2, p:50, short:"Naqi Water Co."},
  {id:"lst_2283", n:"First Milling Co.", s:"consumer_stap", t:2, p:50, short:"First Milling Co."},
  {id:"lst_2284", n:"Modern Mills Co.", s:"consumer_stap", t:2, p:50, short:"Modern Mills Co."},
  {id:"lst_2285", n:"Arabian Mills for Food Products Co.", s:"consumer_stap", t:2, p:50, short:"2285"},
  {id:"lst_2286", n:"Fourth Milling Co.", s:"consumer_stap", t:2, p:50, short:"Fourth Milling Co."},
  {id:"lst_2287", n:"Entaj Co.", s:"consumer_stap", t:2, p:50, short:"Entaj Co."},
  {id:"lst_2288", n:"Nofoth Food Products Co.", s:"consumer_stap", t:2, p:50, short:"2288"},
  {id:"lst_4080", n:"Sinad Holding Co.", s:"consumer_stap", t:2, p:50, short:"Sinad Holding Co."},
  {id:"lst_6001", n:"Halwani Bros Co. (HB)", s:"consumer_stap", t:2, p:50, short:"6001"},
  {id:"lst_6010", n:"National Agriculture Development Co. (Nadec)", s:"consumer_stap", t:2, p:50, short:"6010"},
  {id:"lst_6020", n:"Gulf Agriculture and Food Company Co. (GACO)", s:"consumer_stap", t:2, p:50, short:"6020"},
  {id:"lst_6040", n:"Al Jouf Agricultural Development Co. (TADCO)", s:"consumer_stap", t:2, p:50, short:"6040"},
  {id:"lst_6050", n:"Saudi Fisheries Co. (SFICO)", s:"consumer_stap", t:2, p:50, short:"6050"},
  {id:"lst_6060", n:"Sharqiyah Development Co.", s:"consumer_stap", t:2, p:50, short:"6060"},
  {id:"lst_6070", n:"Al Jouf Agricultural Development Co. (ALJOUF)", s:"consumer_stap", t:2, p:50, short:"6070"},
  {id:"lst_6090", n:"Jazan Development Co. (JAZADCO)", s:"consumer_stap", t:2, p:50, short:"6090"},
  {id:"lst_2140", n:"Ayyan Investment Co.", s:"health", t:2, p:50, short:"Ayyan Investment Co."},
  {id:"lst_2230", n:"Saudi Chemical Co.", s:"health", t:2, p:50, short:"Saudi Chemical Co."},
  {id:"lst_4002", n:"Mouwasat Medical Services Co.", s:"health", t:2, p:50, short:"4002"},
  {id:"lst_4004", n:"Dallah Healthcare Holding Co.", s:"health", t:2, p:50, short:"4004"},
  {id:"lst_4005", n:"Care National Medical and Rehabilitation Center Co.", s:"health", t:2, p:50, short:"4005"},
  {id:"lst_4007", n:"Al Hammadi Holding Co.", s:"health", t:2, p:50, short:"4007"},
  {id:"lst_4009", n:"Saudi German Health", s:"health", t:2, p:50, short:"Saudi German Health"},
  {id:"lst_4014", n:"Middle East Healthcare Co. (Equipment House)", s:"health", t:2, p:50, short:"4014"},
  {id:"lst_4017", n:"Dr. Soliman Fakeeh Care Co.", s:"health", t:2, p:50, short:"4017"},
  {id:"lst_4018", n:"Almoosa Health Co.", s:"health", t:2, p:50, short:"Almoosa Health Co."},
  {id:"lst_4019", n:"SMC Healthcare Co.", s:"health", t:2, p:50, short:"SMC Healthcare Co."},
  {id:"lst_4021", n:"Canadian Medical Center Co. (CMCER)", s:"health", t:2, p:50, short:"4021"},
  {id:"lst_2070", n:"Saudi Pharmaceutical Industries and Medical Appliances Corp. (SPIMACO)", s:"health", t:2, p:50, short:"2070"},
  {id:"lst_4015", n:"Jamjoom Pharmaceuticals Factory Co.", s:"health", t:2, p:50, short:"4015"},
  {id:"lst_4016", n:"Avalon Pharma (Middle East Pharmaceutical Industries Co.)", s:"health", t:2, p:50, short:"4016"},
  {id:"lst_1010", n:"Riyad Bank", s:"finance", t:2, p:50, short:"Riyad Bank"},
  {id:"lst_1020", n:"Bank Aljazira", s:"finance", t:2, p:50, short:"Bank Aljazira"},
  {id:"lst_1030", n:"Saudi Investment Bank (SAIB)", s:"finance", t:2, p:50, short:"1030"},
  {id:"lst_1050", n:"Banque Saudi Fransi", s:"finance", t:2, p:50, short:"Banque Saudi Fransi"},
  {id:"lst_1080", n:"Arab National Bank", s:"finance", t:2, p:50, short:"Arab National Bank"},
  {id:"lst_1140", n:"Bank Albilad", s:"finance", t:2, p:50, short:"Bank Albilad"},
  {id:"lst_1150", n:"Alinma Bank", s:"finance", t:2, p:50, short:"Alinma Bank"},
  {id:"lst_1182", n:"Amlak International Finance Co.", s:"finance", t:2, p:50, short:"1182"},
  {id:"lst_1183", n:"SHL Finance Co.", s:"finance", t:2, p:50, short:"SHL Finance Co."},
  {id:"lst_2120", n:"Saudi Investment Recycling Co. (SAIC)", s:"finance", t:2, p:50, short:"2120"},
  {id:"lst_4081", n:"Nayifat Finance Co.", s:"finance", t:2, p:50, short:"Nayifat Finance Co."},
  {id:"lst_4082", n:"Marn (MRNA) Financial Co.", s:"finance", t:2, p:50, short:"4082"},
  {id:"lst_4083", n:"Tasheel Finance Co.", s:"finance", t:2, p:50, short:"Tasheel Finance Co."},
  {id:"lst_4084", n:"Derayah Financial Co.", s:"finance", t:2, p:50, short:"4084"},
  {id:"lst_4130", n:"Saudi Darb Investment Co.", s:"finance", t:2, p:50, short:"4130"},
  {id:"lst_8010", n:"Company for Cooperative Insurance (Tawuniya)", s:"finance", t:2, p:50, short:"8010"},
  {id:"lst_8012", n:"Aljazira Takaful Taawuni Co.", s:"finance", t:2, p:50, short:"8012"},
  {id:"lst_8030", n:"Mediterranean and Gulf Insurance and Reinsurance Co. (MEDGULF)", s:"finance", t:2, p:50, short:"8030"},
  {id:"lst_8040", n:"Al Sagr Cooperative Insurance Co. (Mutakamela)", s:"finance", t:2, p:50, short:"8040"},
  {id:"lst_8050", n:"Salama Cooperative Insurance Co.", s:"finance", t:2, p:50, short:"8050"},
  {id:"lst_8060", n:"Walaa Cooperative Insurance Co.", s:"finance", t:2, p:50, short:"8060"},
  {id:"lst_8070", n:"Arabian Shield Cooperative Insurance Co.", s:"finance", t:2, p:50, short:"8070"},
  {id:"lst_8100", n:"Saudi Arabian Cooperative Insurance Co. (SAICO)", s:"finance", t:2, p:50, short:"8100"},
  {id:"lst_8120", n:"Gulf Union Alahlia Cooperative Insurance Co.", s:"finance", t:2, p:50, short:"8120"},
  {id:"lst_8150", n:"Allied Cooperative Insurance Group (ACIG)", s:"finance", t:2, p:50, short:"8150"},
  {id:"lst_8160", n:"Al Alamiya for Cooperative Insurance Co. (AICC)", s:"finance", t:2, p:50, short:"8160"},
  {id:"lst_8170", n:"Al Etihad Cooperative Insurance Co.", s:"finance", t:2, p:50, short:"8170"},
  {id:"lst_8190", n:"United Cooperative Assurance Co. (UCA)", s:"finance", t:2, p:50, short:"8190"},
  {id:"lst_8200", n:"Saudi Reinsurance Co. (Saudi Re)", s:"finance", t:2, p:50, short:"8200"},
  {id:"lst_8210", n:"Bupa Arabia for Cooperative Insurance Co.", s:"finance", t:2, p:50, short:"8210"},
  {id:"lst_8240", n:"Chubb Arabia Cooperative Insurance Co.", s:"finance", t:2, p:50, short:"8240"},
  {id:"lst_8260", n:"Gulf General Cooperative Insurance Co.", s:"finance", t:2, p:50, short:"8260"},
  {id:"lst_8280", n:"LIVA Insurance (Saudi Enaya/AXA Cooperative)", s:"finance", t:2, p:50, short:"8280"},
  {id:"lst_8300", n:"Wataniya Insurance Co.", s:"finance", t:2, p:50, short:"8300"},
  {id:"lst_8310", n:"Amana Cooperative Insurance Co.", s:"finance", t:2, p:50, short:"8310"},
  {id:"lst_8311", n:"Enaya Cooperative Insurance Co.", s:"finance", t:2, p:50, short:"8311"},
  {id:"lst_8313", n:"Rasan Information Technology Co.", s:"finance", t:2, p:50, short:"8313"},
  {id:"lst_7030", n:"Zain Saudi Arabia", s:"comm", t:2, p:50, short:"Zain Saudi Arabia"},
  {id:"lst_7040", n:"Go Telecom (Etihad Atheeb Telecommunication Co.)", s:"comm", t:2, p:50, short:"7040"},
  {id:"lst_2081", n:"Alkhorayef Water and Power Technologies Co.", s:"utilities", t:2, p:50, short:"2081"},
  {id:"lst_2083", n:"Marafiq (Power and Water Utility Company for Jubail and Yanbu)", s:"utilities", t:2, p:50, short:"2083"},
  {id:"lst_2084", n:"Miahona Holding Co.", s:"utilities", t:2, p:50, short:"Miahona Holding Co."},
  {id:"lst_4020", n:"Saudi Real Estate Co. (Alakaria)", s:"realestate", t:2, p:50, short:"4020"},
  {id:"lst_4090", n:"Taiba Investments Co.", s:"realestate", t:2, p:50, short:"4090"},
  {id:"lst_4100", n:"Makkah Construction and Development Co. (MCDC)", s:"realestate", t:2, p:50, short:"4100"},
  {id:"lst_4150", n:"Arriyadh Development Co. (ARDCO)", s:"realestate", t:2, p:50, short:"4150"},
  {id:"lst_4230", n:"Red Sea International Co.", s:"realestate", t:2, p:50, short:"4230"},
  {id:"lst_4250", n:"Jabal Omar Development Co.", s:"realestate", t:2, p:50, short:"4250"},
  {id:"lst_4300", n:"Dar Al Arkan Real Estate Development Co.", s:"realestate", t:2, p:50, short:"4300"},
  {id:"lst_4310", n:"Knowledge Economic City (KEC)", s:"realestate", t:2, p:50, short:"4310"},
  {id:"lst_4320", n:"Al Andalus Property Co.", s:"realestate", t:2, p:50, short:"4320"},
  {id:"lst_4321", n:"Cenomi Centers (Arabian Centres Co.)", s:"realestate", t:2, p:50, short:"4321"},
  {id:"lst_4322", n:"Retal Urban Development Co.", s:"realestate", t:2, p:50, short:"4322"},
  {id:"lst_4323", n:"Sumou Real Estate Co.", s:"realestate", t:2, p:50, short:"4323"},
  {id:"lst_4324", n:"Banan Real Estate Co.", s:"realestate", t:2, p:50, short:"4324"},
  {id:"lst_4325", n:"Masar Al Jazira Real Estate Development Co.", s:"realestate", t:2, p:50, short:"4325"},
  {id:"lst_4326", n:"Almajdiah Real Estate Co.", s:"realestate", t:2, p:50, short:"4326"},
  {id:"lst_4327", n:"Al Ramz Real Estate Co.", s:"realestate", t:2, p:50, short:"4327"},
  {id:"lst_4328", n:"Ladun Investment Co.", s:"realestate", t:2, p:50, short:"Ladun Investment Co."},
  {id:"lst_4330", n:"Riyad REIT Fund", s:"realestate", t:2, p:50, short:"Riyad REIT Fund"},
  {id:"lst_4331", n:"Aljazira REIT Fund", s:"realestate", t:2, p:50, short:"Aljazira REIT Fund"},
  {id:"lst_4332", n:"Jadwa REIT Al Haramain Fund", s:"realestate", t:2, p:50, short:"4332"},
  {id:"lst_4333", n:"Taleem REIT Fund", s:"realestate", t:2, p:50, short:"Taleem REIT Fund"},
  {id:"lst_4334", n:"Al Maather REIT Fund", s:"realestate", t:2, p:50, short:"Al Maather REIT Fund"},
  {id:"lst_4335", n:"Musharaka REIT Fund", s:"realestate", t:2, p:50, short:"Musharaka REIT Fund"},
  {id:"lst_4336", n:"Mulkia Gulf REIT Fund", s:"realestate", t:2, p:50, short:"4336"},
  {id:"lst_4337", n:"Al Aziziah REIT Fund", s:"realestate", t:2, p:50, short:"Al Aziziah REIT Fund"},
  {id:"lst_4338", n:"SNB Capital Diversified REIT Fund (Alahli REIT 1)", s:"realestate", t:2, p:50, short:"4338"},
  {id:"lst_4339", n:"Derayah REIT Fund", s:"realestate", t:2, p:50, short:"Derayah REIT Fund"},
  {id:"lst_4342", n:"Jadwa REIT Saudi Fund", s:"realestate", t:2, p:50, short:"4342"},
  {id:"lst_4344", n:"Sedco Capital REIT Fund", s:"realestate", t:2, p:50, short:"4344"},
  {id:"lst_4345", n:"Alinma Retail REIT Fund", s:"realestate", t:2, p:50, short:"4345"},
  {id:"lst_4346", n:"MEFIC REIT Fund", s:"realestate", t:2, p:50, short:"MEFIC REIT Fund"},
  {id:"lst_4347", n:"Bonyan REIT Fund", s:"realestate", t:2, p:50, short:"Bonyan REIT Fund"},
  {id:"lst_4348", n:"Alkhabeer REIT Fund", s:"realestate", t:2, p:50, short:"Alkhabeer REIT Fund"},
  {id:"lst_4349", n:"Alinma Hospitality REIT Fund", s:"realestate", t:2, p:50, short:"4349"},
  {id:"lst_4350", n:"Alistithmar REIT Fund (AREIC Diversified REIT)", s:"realestate", t:2, p:50, short:"4350"},
  {id:"lst_7200", n:"Middle East Internet Services Co. (MIS)", s:"tech", t:2, p:50, short:"7200"},
  {id:"lst_7201", n:"Arab Sea Information Systems Co.", s:"tech", t:2, p:50, short:"7201"},
  {id:"lst_7202", n:"Al Moammar Information Systems Co. (Solutions)", s:"tech", t:2, p:50, short:"7202"},
  {id:"lst_7203", n:"Elm Co.", s:"tech", t:2, p:50, short:"Elm Co."},
  {id:"lst_7204", n:"2P Perfect Presentation for Commercial Services Co.", s:"tech", t:2, p:50, short:"7204"},
  {id:"lst_7205", n:"Al-Dawaa Business Solutions Co. (DBS)", s:"tech", t:2, p:50, short:"7205"},
  {id:"lst_7211", n:"Saudi Azm for Communication and Information Technology Co.", s:"tech", t:2, p:50, short:"7211"},
  {id:"lst_4165", n:"Almajed for Oud Co.", s:"consumer_stap", t:2, p:50, short:"Almajed for Oud Co."},
];

const PEOPLE = [
  {id:"kingsalman", n:"King Salman bin Abdulaziz Al Saud", t:0, p:94, s:"gov", roles:[
    ["royalcourt","King of Saudi Arabia · Custodian of the Two Holy Mosques","political","v"]]},
  {id:"mbs", n:"Crown Prince Mohammed bin Salman Al Saud", t:0, p:100, s:"gov", roles:[
    ["royalcourt","Crown Prince","political","v"],
    ["com","Prime Minister","political","v"],
    ["pif","Chairman","board","v"]],
    note:"'MBS' — runs the state, the sovereign fund and Vision 2030. Every giga-project chain ends here."},
  {id:"kbs", n:"Prince Khalid bin Salman Al Saud", t:0, p:88, s:"gov", roles:[
    ["mod_sa","Minister of Defense","political","v"]],
    note:"MBS's full brother."},
  {id:"abs", n:"Prince Abdulaziz bin Salman Al Saud", t:0, p:90, s:"energy", roles:[
    ["moenergy","Minister of Energy","political","v"]],
    note:"Half-brother of MBS; OPEC+ strategy runs through him."},
  {id:"faisal_farhan", n:"Prince Faisal bin Farhan Al Saud", t:0, p:86, s:"gov", roles:[
    ["mofa_sa","Minister of Foreign Affairs","political","v"]]},
  {id:"alwaleed", n:"Prince Alwaleed bin Talal Al Saud", t:0, p:78, s:"conglomerate", roles:[
    ["kingdomholding","Chairman","board","v"]]},
  {id:"rumayyan", n:"Yasir Al-Rumayyan", t:1, p:92, s:"sovereign", roles:[
    ["pif","Governor","executive","v"],
    ["aramco","Chairman","board","v"]],
    note:"MBS's chief capital allocator — PIF, Aramco board, Newcastle United, LIV Golf."},
  {id:"nasser_aramco", n:"Amin Nasser", t:1, p:88, s:"energy", roles:[
    ["aramco","President & CEO","executive","v"]]},
  {id:"jadaan", n:"Mohammed Al-Jadaan", t:1, p:86, s:"finance", roles:[
    ["mof_sa","Minister of Finance","political","v"]]},
  {id:"falih", n:"Khalid Al-Falih", t:1, p:84, s:"gov", roles:[
    ["misa","Minister of Investment","political","v"]]},
  {id:"alswaha", n:"Abdullah Alswaha", t:1, p:78, s:"tech", roles:[
    ["mcit_sa","Minister of Communications & IT","political","v"]]},
  {id:"khateeb", n:"Ahmed Al-Khateeb", t:1, p:76, s:"gov", roles:[
    ["mot_sa","Minister of Tourism","political","v"]]},
  {id:"alkhorayef", n:"Bandar Alkhorayef", t:1, p:74, s:"industry", roles:[
    ["moind","Minister of Industry & Mineral Resources","political","v"]]},
  {id:"qasabi", n:"Majid Al-Qasabi", t:1, p:76, s:"gov", roles:[
    ["moc_sa","Minister of Commerce","political","v"]]},
  {id:"alsayari", n:"Ayman Al-Sayari", t:1, p:78, s:"finance", roles:[
    ["sama","Governor","executive","v"]]},
  {id:"alalshikh", n:"Turki Alalshikh", t:1, p:82, s:"gov", roles:[
    ["gea","Chairman","government","v"]],
    note:"Entertainment, boxing and events czar; one of the most visible operators of the MBS era."},
  {id:"alghamdi_sdaia", n:"Abdullah Al-Ghamdi", t:2, p:70, s:"tech", roles:[
    ["sdaia","President","government","ns"]]},
  {id:"fageeh", n:"Abdulrahman Al-Fageeh", t:2, p:72, s:"materials", roles:[
    ["sabic","CEO","executive","ns"]]},
  {id:"wilt", n:"Bob Wilt", t:2, p:68, s:"materials", roles:[
    ["maaden","CEO","executive","ns"]]},
  {id:"alwetaid", n:"Olayan Alwetaid", t:2, p:70, s:"comm", roles:[
    ["stc","Group CEO","executive","ns"]]},
  {id:"abunayyan", n:"Mohammad Abunayyan", t:2, p:76, s:"utilities", roles:[
    ["acwa","Founder & Chairman","board","v"]]},
  {id:"tareq_amin", n:"Tareq Amin", t:2, p:72, s:"tech", roles:[
    ["humain","CEO","executive","ns"]]},
  {id:"amit_midha", n:"Amit Midha", t:2, p:64, s:"tech", roles:[
    ["alat","CEO","executive","ns"]]},
  {id:"tony_douglas", n:"Tony Douglas", t:2, p:70, s:"industry", roles:[
    ["riyadhair","CEO","executive","v"]]},
  {id:"pagano", n:"John Pagano", t:2, p:64, s:"realestate", roles:[
    ["redsea","Group CEO","executive","v"]]},
  {id:"inzerillo", n:"Jerry Inzerillo", t:2, p:66, s:"consumer_disc", roles:[
    ["diriyah","Group CEO","executive","v"]]},
  {id:"almudaifer", n:"Aiman Al-Mudaifer", t:2, p:68, s:"realestate", roles:[
    ["neom","CEO (acting)","executive","ns"]]},
  {id:"waleed_ibrahim", n:"Waleed Al Ibrahim", t:2, p:72, s:"comm", roles:[
    ["mbcgroup","Founder & Chairman","board","v"]]},
  {id:"lubna", n:"Lubna Olayan", t:2, p:76, s:"finance", roles:[
    ["olayan","Chair, Olayan Financing","board","v"],
    ["sab","Chair","board","ns"]]},
  {id:"alsadhan", n:"Tareq Al-Sadhan", t:2, p:72, s:"finance", roles:[
    ["snb","Group CEO","executive","v"]]},
  {id:"saeed_alghamdi", n:"Saeed Al-Ghamdi", t:2, p:72, s:"finance", roles:[
    ["snb","Chairman","board","ns"]]},
  {id:"almogbel", n:"Waleed Al-Mogbel", t:2, p:72, s:"finance", roles:[
    ["alrajhi","CEO & Managing Director","executive","v"]]},
  {id:"alghonon", n:"Khalid Al-Ghonon", t:2, p:66, s:"utilities", roles:[
    ["sec","CEO","executive","ns"]]},
  {id:"alhussan", n:"Khalid Al-Hussan", t:2, p:70, s:"finance", roles:[
    ["tadawul","Group CEO, Saudi Tadawul Group","executive","v"]]},
  {id:"alomar_saudia", n:"Ibrahim Al-Omar", t:2, p:68, s:"industry", roles:[
    ["saudia","Director General, Saudia Group","executive","v"]]},
  {id:"almuhid", n:"Thamer AlMuhid", t:2, p:68, s:"industry", roles:[
    ["sami","CEO","executive","v"]]},
  {id:"sulaiman_alhabib", n:"Sulaiman Al Habib", t:2, p:74, s:"health", roles:[
    ["habib","Founder & Chairman","board","v"]]},
  {id:"atallah", n:"Noman Atallah", t:2, p:64, s:"realestate", roles:[
    ["roshn","Group CEO","executive","ns"]]},
  {id:"aldawood", n:"Abdullah Aldawood", t:2, p:68, s:"consumer_disc", roles:[
    ["qiddiya","CEO & Managing Director","executive","v"]]},
  {id:"aljasser", n:"Fawaz Al-Jasser", t:2, p:64, s:"consumer_stap", roles:[
    ["almarai","CEO","executive","ns"]]},
  {id:"jomana", n:"Jomana Al-Rashid", t:2, p:68, s:"comm", roles:[
    ["srmg","CEO","executive","v"]]},
  {id:"alajlan", n:"Ajlan bin Abdulaziz Al Ajlan", t:2, p:68, s:"conglomerate", roles:[
    ["ajlan","Founder & Chairman","board","v"]]},
];

const OWNERSHIP = [
  ["com","royalcourt","governs under"],
  ["mof_sa","com"],["mofa_sa","com"],["mod_sa","com"],["moenergy","com"],["misa","com"],
  ["mcit_sa","com"],["moc_sa","com"],["moind","com"],["mot_sa","com"],
  ["sama","royalcourt"],["sdaia","royalcourt"],["gea","royalcourt"],
  ["pif","royalcourt","sovereign fund"],
  ["aramco","royalcourt","state majority"],
  ["sabic","aramco","70% shareholder"],
  ["maaden","pif","majority","ns"],
  ["stc","pif","majority"],
  ["sec","pif","majority","ns"],
  ["snb","pif","anchor shareholder"],
  ["tadawul","pif","majority","ns"],
  ["neom","pif"],["redsea","pif"],["qiddiya","pif"],["diriyah","pif"],["roshn","pif"],
  ["humain","pif"],["alat","pif"],
  ["saudia","pif","transferred to","ns"],
  ["riyadhair","pif"],
  ["sami","pif"],
  ["srmg","royalcourt","royal-linked","ns"],
  ["mbcgroup","royalcourt","state-controlled since 2018","ns"],
  ["almarai","pif","strategic stake","ns"],
  ["acwa","pif","44% shareholder","ns"],
  ["lst_2030","tadawul","listed on Tadawul","ns"],
  ["lst_2380","tadawul","listed on Tadawul","ns"],
  ["lst_4030","tadawul","listed on Tadawul","ns"],
  ["lst_2381","tadawul","listed on Tadawul","ns"],
  ["lst_2382","tadawul","listed on Tadawul","ns"],
  ["lst_1201","tadawul","listed on Tadawul","ns"],
  ["lst_1202","tadawul","listed on Tadawul","ns"],
  ["lst_1210","tadawul","listed on Tadawul","ns"],
  ["lst_1301","tadawul","listed on Tadawul","ns"],
  ["lst_1304","tadawul","listed on Tadawul","ns"],
  ["lst_1320","tadawul","listed on Tadawul","ns"],
  ["lst_2001","tadawul","listed on Tadawul","ns"],
  ["lst_2090","tadawul","listed on Tadawul","ns"],
  ["lst_2150","tadawul","listed on Tadawul","ns"],
  ["lst_2170","tadawul","listed on Tadawul","ns"],
  ["lst_2180","tadawul","listed on Tadawul","ns"],
  ["lst_2200","tadawul","listed on Tadawul","ns"],
  ["lst_2210","tadawul","listed on Tadawul","ns"],
  ["lst_2220","tadawul","listed on Tadawul","ns"],
  ["lst_2240","tadawul","listed on Tadawul","ns"],
  ["lst_2250","tadawul","listed on Tadawul","ns"],
  ["lst_2290","tadawul","listed on Tadawul","ns"],
  ["lst_2300","tadawul","listed on Tadawul","ns"],
  ["lst_2310","tadawul","listed on Tadawul","ns"],
  ["lst_2330","tadawul","listed on Tadawul","ns"],
  ["lst_2350","tadawul","listed on Tadawul","ns"],
  ["lst_2360","tadawul","listed on Tadawul","ns"],
  ["lst_3002","tadawul","listed on Tadawul","ns"],
  ["lst_3003","tadawul","listed on Tadawul","ns"],
  ["lst_3004","tadawul","listed on Tadawul","ns"],
  ["lst_3005","tadawul","listed on Tadawul","ns"],
  ["lst_3007","tadawul","listed on Tadawul","ns"],
  ["lst_3008","tadawul","listed on Tadawul","ns"],
  ["lst_3010","tadawul","listed on Tadawul","ns"],
  ["lst_3020","tadawul","listed on Tadawul","ns"],
  ["lst_3030","tadawul","listed on Tadawul","ns"],
  ["lst_3040","tadawul","listed on Tadawul","ns"],
  ["lst_3050","tadawul","listed on Tadawul","ns"],
  ["lst_3060","tadawul","listed on Tadawul","ns"],
  ["lst_3080","tadawul","listed on Tadawul","ns"],
  ["lst_3090","tadawul","listed on Tadawul","ns"],
  ["lst_3091","tadawul","listed on Tadawul","ns"],
  ["lst_3092","tadawul","listed on Tadawul","ns"],
  ["lst_2060","tadawul","listed on Tadawul","ns"],
  ["lst_1321","tadawul","listed on Tadawul","ns"],
  ["lst_1322","tadawul","listed on Tadawul","ns"],
  ["lst_1323","tadawul","listed on Tadawul","ns"],
  ["lst_1324","tadawul","listed on Tadawul","ns"],
  ["lst_1212","tadawul","listed on Tadawul","ns"],
  ["lst_1302","tadawul","listed on Tadawul","ns"],
  ["lst_1303","tadawul","listed on Tadawul","ns"],
  ["lst_1214","tadawul","listed on Tadawul","ns"],
  ["lst_2040","tadawul","listed on Tadawul","ns"],
  ["lst_2110","tadawul","listed on Tadawul","ns"],
  ["lst_2160","tadawul","listed on Tadawul","ns"],
  ["lst_2320","tadawul","listed on Tadawul","ns"],
  ["lst_2370","tadawul","listed on Tadawul","ns"],
  ["lst_4110","tadawul","listed on Tadawul","ns"],
  ["lst_4140","tadawul","listed on Tadawul","ns"],
  ["lst_4141","tadawul","listed on Tadawul","ns"],
  ["lst_4142","tadawul","listed on Tadawul","ns"],
  ["lst_4144","tadawul","listed on Tadawul","ns"],
  ["lst_4145","tadawul","listed on Tadawul","ns"],
  ["lst_4146","tadawul","listed on Tadawul","ns"],
  ["lst_4147","tadawul","listed on Tadawul","ns"],
  ["lst_4148","tadawul","listed on Tadawul","ns"],
  ["lst_1831","tadawul","listed on Tadawul","ns"],
  ["lst_1832","tadawul","listed on Tadawul","ns"],
  ["lst_1833","tadawul","listed on Tadawul","ns"],
  ["lst_1834","tadawul","listed on Tadawul","ns"],
  ["lst_1835","tadawul","listed on Tadawul","ns"],
  ["lst_4270","tadawul","listed on Tadawul","ns"],
  ["lst_6004","tadawul","listed on Tadawul","ns"],
  ["lst_2190","tadawul","listed on Tadawul","ns"],
  ["lst_4031","tadawul","listed on Tadawul","ns"],
  ["lst_4040","tadawul","listed on Tadawul","ns"],
  ["lst_4260","tadawul","listed on Tadawul","ns"],
  ["lst_4261","tadawul","listed on Tadawul","ns"],
  ["lst_4262","tadawul","listed on Tadawul","ns"],
  ["lst_4263","tadawul","listed on Tadawul","ns"],
  ["lst_4264","tadawul","listed on Tadawul","ns"],
  ["lst_4265","tadawul","listed on Tadawul","ns"],
  ["lst_1213","tadawul","listed on Tadawul","ns"],
  ["lst_2130","tadawul","listed on Tadawul","ns"],
  ["lst_2340","tadawul","listed on Tadawul","ns"],
  ["lst_4011","tadawul","listed on Tadawul","ns"],
  ["lst_4012","tadawul","listed on Tadawul","ns"],
  ["lst_4180","tadawul","listed on Tadawul","ns"],
  ["lst_1810","tadawul","listed on Tadawul","ns"],
  ["lst_1820","tadawul","listed on Tadawul","ns"],
  ["lst_1830","tadawul","listed on Tadawul","ns"],
  ["lst_4170","tadawul","listed on Tadawul","ns"],
  ["lst_4290","tadawul","listed on Tadawul","ns"],
  ["lst_4291","tadawul","listed on Tadawul","ns"],
  ["lst_4292","tadawul","listed on Tadawul","ns"],
  ["lst_6002","tadawul","listed on Tadawul","ns"],
  ["lst_6012","tadawul","listed on Tadawul","ns"],
  ["lst_6013","tadawul","listed on Tadawul","ns"],
  ["lst_6014","tadawul","listed on Tadawul","ns"],
  ["lst_6015","tadawul","listed on Tadawul","ns"],
  ["lst_6016","tadawul","listed on Tadawul","ns"],
  ["lst_6017","tadawul","listed on Tadawul","ns"],
  ["lst_6018","tadawul","listed on Tadawul","ns"],
  ["lst_6019","tadawul","listed on Tadawul","ns"],
  ["lst_6022","tadawul","listed on Tadawul","ns"],
  ["lst_4070","tadawul","listed on Tadawul","ns"],
  ["lst_4071","tadawul","listed on Tadawul","ns"],
  ["lst_4072","tadawul","listed on Tadawul","ns"],
  ["lst_4003","tadawul","listed on Tadawul","ns"],
  ["lst_4008","tadawul","listed on Tadawul","ns"],
  ["lst_4050","tadawul","listed on Tadawul","ns"],
  ["lst_4051","tadawul","listed on Tadawul","ns"],
  ["lst_4190","tadawul","listed on Tadawul","ns"],
  ["lst_4191","tadawul","listed on Tadawul","ns"],
  ["lst_4192","tadawul","listed on Tadawul","ns"],
  ["lst_4193","tadawul","listed on Tadawul","ns"],
  ["lst_4194","tadawul","listed on Tadawul","ns"],
  ["lst_4200","tadawul","listed on Tadawul","ns"],
  ["lst_4240","tadawul","listed on Tadawul","ns"],
  ["lst_4001","tadawul","listed on Tadawul","ns"],
  ["lst_4006","tadawul","listed on Tadawul","ns"],
  ["lst_4061","tadawul","listed on Tadawul","ns"],
  ["lst_4160","tadawul","listed on Tadawul","ns"],
  ["lst_4161","tadawul","listed on Tadawul","ns"],
  ["lst_4162","tadawul","listed on Tadawul","ns"],
  ["lst_4163","tadawul","listed on Tadawul","ns"],
  ["lst_4164","tadawul","listed on Tadawul","ns"],
  ["lst_2050","tadawul","listed on Tadawul","ns"],
  ["lst_2100","tadawul","listed on Tadawul","ns"],
  ["lst_2281","tadawul","listed on Tadawul","ns"],
  ["lst_2282","tadawul","listed on Tadawul","ns"],
  ["lst_2283","tadawul","listed on Tadawul","ns"],
  ["lst_2284","tadawul","listed on Tadawul","ns"],
  ["lst_2285","tadawul","listed on Tadawul","ns"],
  ["lst_2286","tadawul","listed on Tadawul","ns"],
  ["lst_2287","tadawul","listed on Tadawul","ns"],
  ["lst_2288","tadawul","listed on Tadawul","ns"],
  ["lst_4080","tadawul","listed on Tadawul","ns"],
  ["lst_6001","tadawul","listed on Tadawul","ns"],
  ["lst_6010","tadawul","listed on Tadawul","ns"],
  ["lst_6020","tadawul","listed on Tadawul","ns"],
  ["lst_6040","tadawul","listed on Tadawul","ns"],
  ["lst_6050","tadawul","listed on Tadawul","ns"],
  ["lst_6060","tadawul","listed on Tadawul","ns"],
  ["lst_6070","tadawul","listed on Tadawul","ns"],
  ["lst_6090","tadawul","listed on Tadawul","ns"],
  ["lst_2140","tadawul","listed on Tadawul","ns"],
  ["lst_2230","tadawul","listed on Tadawul","ns"],
  ["lst_4002","tadawul","listed on Tadawul","ns"],
  ["lst_4004","tadawul","listed on Tadawul","ns"],
  ["lst_4005","tadawul","listed on Tadawul","ns"],
  ["lst_4007","tadawul","listed on Tadawul","ns"],
  ["lst_4009","tadawul","listed on Tadawul","ns"],
  ["lst_4014","tadawul","listed on Tadawul","ns"],
  ["lst_4017","tadawul","listed on Tadawul","ns"],
  ["lst_4018","tadawul","listed on Tadawul","ns"],
  ["lst_4019","tadawul","listed on Tadawul","ns"],
  ["lst_4021","tadawul","listed on Tadawul","ns"],
  ["lst_2070","tadawul","listed on Tadawul","ns"],
  ["lst_4015","tadawul","listed on Tadawul","ns"],
  ["lst_4016","tadawul","listed on Tadawul","ns"],
  ["lst_1010","tadawul","listed on Tadawul","ns"],
  ["lst_1020","tadawul","listed on Tadawul","ns"],
  ["lst_1030","tadawul","listed on Tadawul","ns"],
  ["lst_1050","tadawul","listed on Tadawul","ns"],
  ["lst_1080","tadawul","listed on Tadawul","ns"],
  ["lst_1140","tadawul","listed on Tadawul","ns"],
  ["lst_1150","tadawul","listed on Tadawul","ns"],
  ["lst_1182","tadawul","listed on Tadawul","ns"],
  ["lst_1183","tadawul","listed on Tadawul","ns"],
  ["lst_2120","tadawul","listed on Tadawul","ns"],
  ["lst_4081","tadawul","listed on Tadawul","ns"],
  ["lst_4082","tadawul","listed on Tadawul","ns"],
  ["lst_4083","tadawul","listed on Tadawul","ns"],
  ["lst_4084","tadawul","listed on Tadawul","ns"],
  ["lst_4130","tadawul","listed on Tadawul","ns"],
  ["lst_8010","tadawul","listed on Tadawul","ns"],
  ["lst_8012","tadawul","listed on Tadawul","ns"],
  ["lst_8030","tadawul","listed on Tadawul","ns"],
  ["lst_8040","tadawul","listed on Tadawul","ns"],
  ["lst_8050","tadawul","listed on Tadawul","ns"],
  ["lst_8060","tadawul","listed on Tadawul","ns"],
  ["lst_8070","tadawul","listed on Tadawul","ns"],
  ["lst_8100","tadawul","listed on Tadawul","ns"],
  ["lst_8120","tadawul","listed on Tadawul","ns"],
  ["lst_8150","tadawul","listed on Tadawul","ns"],
  ["lst_8160","tadawul","listed on Tadawul","ns"],
  ["lst_8170","tadawul","listed on Tadawul","ns"],
  ["lst_8190","tadawul","listed on Tadawul","ns"],
  ["lst_8200","tadawul","listed on Tadawul","ns"],
  ["lst_8210","tadawul","listed on Tadawul","ns"],
  ["lst_8240","tadawul","listed on Tadawul","ns"],
  ["lst_8260","tadawul","listed on Tadawul","ns"],
  ["lst_8280","tadawul","listed on Tadawul","ns"],
  ["lst_8300","tadawul","listed on Tadawul","ns"],
  ["lst_8310","tadawul","listed on Tadawul","ns"],
  ["lst_8311","tadawul","listed on Tadawul","ns"],
  ["lst_8313","tadawul","listed on Tadawul","ns"],
  ["lst_7030","tadawul","listed on Tadawul","ns"],
  ["lst_7040","tadawul","listed on Tadawul","ns"],
  ["lst_2081","tadawul","listed on Tadawul","ns"],
  ["lst_2083","tadawul","listed on Tadawul","ns"],
  ["lst_2084","tadawul","listed on Tadawul","ns"],
  ["lst_4020","tadawul","listed on Tadawul","ns"],
  ["lst_4090","tadawul","listed on Tadawul","ns"],
  ["lst_4100","tadawul","listed on Tadawul","ns"],
  ["lst_4150","tadawul","listed on Tadawul","ns"],
  ["lst_4230","tadawul","listed on Tadawul","ns"],
  ["lst_4250","tadawul","listed on Tadawul","ns"],
  ["lst_4300","tadawul","listed on Tadawul","ns"],
  ["lst_4310","tadawul","listed on Tadawul","ns"],
  ["lst_4320","tadawul","listed on Tadawul","ns"],
  ["lst_4321","tadawul","listed on Tadawul","ns"],
  ["lst_4322","tadawul","listed on Tadawul","ns"],
  ["lst_4323","tadawul","listed on Tadawul","ns"],
  ["lst_4324","tadawul","listed on Tadawul","ns"],
  ["lst_4325","tadawul","listed on Tadawul","ns"],
  ["lst_4326","tadawul","listed on Tadawul","ns"],
  ["lst_4327","tadawul","listed on Tadawul","ns"],
  ["lst_4328","tadawul","listed on Tadawul","ns"],
  ["lst_4330","tadawul","listed on Tadawul","ns"],
  ["lst_4331","tadawul","listed on Tadawul","ns"],
  ["lst_4332","tadawul","listed on Tadawul","ns"],
  ["lst_4333","tadawul","listed on Tadawul","ns"],
  ["lst_4334","tadawul","listed on Tadawul","ns"],
  ["lst_4335","tadawul","listed on Tadawul","ns"],
  ["lst_4336","tadawul","listed on Tadawul","ns"],
  ["lst_4337","tadawul","listed on Tadawul","ns"],
  ["lst_4338","tadawul","listed on Tadawul","ns"],
  ["lst_4339","tadawul","listed on Tadawul","ns"],
  ["lst_4342","tadawul","listed on Tadawul","ns"],
  ["lst_4344","tadawul","listed on Tadawul","ns"],
  ["lst_4345","tadawul","listed on Tadawul","ns"],
  ["lst_4346","tadawul","listed on Tadawul","ns"],
  ["lst_4347","tadawul","listed on Tadawul","ns"],
  ["lst_4348","tadawul","listed on Tadawul","ns"],
  ["lst_4349","tadawul","listed on Tadawul","ns"],
  ["lst_4350","tadawul","listed on Tadawul","ns"],
  ["lst_7200","tadawul","listed on Tadawul","ns"],
  ["lst_7201","tadawul","listed on Tadawul","ns"],
  ["lst_7202","tadawul","listed on Tadawul","ns"],
  ["lst_7203","tadawul","listed on Tadawul","ns"],
  ["lst_7204","tadawul","listed on Tadawul","ns"],
  ["lst_7205","tadawul","listed on Tadawul","ns"],
  ["lst_7211","tadawul","listed on Tadawul","ns"],
  ["lst_4165","tadawul","listed on Tadawul","ns"],
];

const FAMILY = [
  ["kingsalman","mbs","father–son"],
  ["kingsalman","kbs","father–son"],
  ["kingsalman","abs","father–son"],
  ["mbs","kbs","brothers"],
  ["mbs","abs","half-brothers"],
];

const AKA = {
  mbs:["Mohammed bin Salman","MBS","Crown Prince Mohammed"],
  kbs:["Khalid bin Salman","KBS"],
  abs:["Abdulaziz bin Salman"],
  rumayyan:["Yasir Al Rumayyan","Al-Rumayyan"],
  nasser_aramco:["Amin Nasser","Amin H. Nasser"],
  pif:["Public Investment Fund"],
  aramco:["Saudi Aramco","Aramco"],
  alalshikh:["Turki Al-Sheikh","Turki Al Sheikh"],
  neom:["NEOM"],
  stc:["Saudi Telecom"],
  alsadhan:["Tareq Abdulrahman Al-Sadhan","Tareq Al Sadhan"],
  almogbel:["Waleed Abdullah Al-Mogbel","Waleed Al Mogbel"],
  alhussan:["Khalid Al Hussan","Khalid Abdullah Al-Hussan"],
  almuhid:["Thamer Al-Muhid","Thamer Al Muhid"],
  sulaiman_alhabib:["Dr. Sulaiman Al-Habib","Sulaiman bin Abdulaziz Al Habib"],
  jomana:["Jomana Alrashid","Jomana Al-Rashed"],
  alajlan:["Ajlan Al Ajlan","Ajlan Abdulaziz Alajlan"],
};
