/* AUTO-GENERATED by tools/match_news.py — do not edit by hand. */
window.NEWS_ITEMS = [
  {id:"2026-09-03_kingdom-holding-completes-224mln-acquisi_17431a", date:"2026-09-03", title:"Kingdom Holding completes $224mln acquisition of 70% stake in Al Hilal Club", source:"Zawya", url:"https://www.zawya.com/en/business/swf/kingdom-holding-completes-224mln-acquisition-of-70-stake-in-al-hilal-club-475064", ids:["kingdomholding"]},
  {id:"2026-09-03_meed-exclusive-aramco-firms-up-plans-for_f70cf3", date:"2026-09-03", title:"MEED EXCLUSIVE Aramco firms up plans for LNG facility in Saudi Arabia", source:"MEED", url:"https://www.meed.com/aramco-firms-up-plans-for-lng-facility-in-saudi-arabia", ids:["aramco"]},
  {id:"2026-09-03_saudi-construction-surges-despite-pif-ta_81ad1a", date:"2026-09-03", title:"Saudi construction surges despite PIF taking a back seat", source:"AGBI", url:"https://www.agbi.com/construction/2026/09/saudi-construction-activity-surges-despite-pif-taking-a-back-seat/", ids:["pif"]},
  {id:"2026-09-03_video-aramco-ventures-invests-in-us-star_d22c1c", date:"2026-09-03", title:"VIDEO: Aramco Ventures invests in US startup Twin1 AI that creates AI worker clones", source:"Zawya", url:"https://www.zawya.com/en/multimedia/video-aramco-ventures-invests-in-us-startup-twin1-ai-that-creates-ai-worker-clones-467965", ids:["aramco"]},
];
window.SUGGESTED_EDGES = [];
