/* AUTO-GENERATED by tools/match_news.py — do not edit by hand. */
window.NEWS_ITEMS = [
  {id:"2026-09-04_5-sharjah-police-arrest-man-accused-of-k_640bde", date:"2026-09-04", title:"5.Sharjah Police arrest man accused of killing two Kazakh sisters", source:"Khaleej Times", url:"https://www.khaleejtimes.com/uae/crime/sharjah-police-arrest-man-accused-of-killing-two-kazakh-sisters?utm_source=google-analytics&utm_medium=section-rcmd-api&utm_campaign=trending-inarticle-section", ids:["shjpolice"]},
  {id:"2026-09-04_air-arabia-adds-more-bangkok-flights-fro_936650", date:"2026-09-04", title:"Air Arabia adds more Bangkok flights from Sharjah1m read", source:"Gulf News", url:"https://gulfnews.com/business/aviation/air-arabia-adds-fourth-daily-bangkok-flight-from-sharjah-1.500663187", ids:["airarabia"]},
  {id:"2026-09-03_uae-based-arada-to-co-develop-7bln-megap_843b9d", date:"2026-09-03", title:"UAE-based Arada to co-develop $7bln megaproject in Syria", source:"Zawya", url:"https://www.zawya.com/en/business/uae-based-arada-to-co-develop-7bln-megaproject-in-syria-474965", ids:["arada"]},
  {id:"2026-09-03_sharjah-police-arrest-kazakh-man-after-t_cdc9dc", date:"2026-09-03", title:"Sharjah Police arrest Kazakh man after two sisters killed", source:"The National", url:"https://www.thenationalnews.com/news/uae/2026/09/03/sharjah-police-arrest-kazakh-man-after-two-sisters-killed/", ids:["shjpolice"]},
  {id:"2026-09-03_sukoon-takaful-ajman-bank-sign-strategic_ab0aa7", date:"2026-09-03", title:"Sukoon Takaful, Ajman Bank sign strategic deal1m read", source:"Gulf News", url:"https://gulfnews.com/business/banking/sukoon-takaful-ajman-bank-sign-sharia-compliant-deal-1.500662203", ids:["ajmanbank"]},
];
window.SUGGESTED_EDGES = [];
