/* AUTO-GENERATED by tools/match_news.py — do not edit by hand. */
window.NEWS_ITEMS = [
  {id:"2026-09-03_uae-based-arada-to-co-develop-7bln-megap_843b9d", date:"2026-09-03", title:"UAE-based Arada to co-develop $7bln megaproject in Syria", source:"Zawya", url:"https://www.zawya.com/en/business/uae-based-arada-to-co-develop-7bln-megaproject-in-syria-474965", ids:["arada"]},
  {id:"2026-09-03_sukoon-takaful-ajman-bank-sign-strategic_ab0aa7", date:"2026-09-03", title:"Sukoon Takaful, Ajman Bank sign strategic dealPartnership will give Ajman Bank customers access to tailored Takaful solutions1h ago1m read", source:"Gulf News", url:"https://gulfnews.com/business/banking/sukoon-takaful-ajman-bank-sign-sharia-compliant-deal-1.500662203", ids:["ajmanbank"]},
];
window.SUGGESTED_EDGES = [];
