/* AUTO-GENERATED by tools/match_news.py — do not edit by hand. */
window.NEWS_ITEMS = [
  {id:"2026-09-03_uae-based-arada-to-co-develop-7bln-megap_843b9d", date:"2026-09-03", title:"UAE-based Arada to co-develop $7bln megaproject in Syria", source:"Zawya", url:"https://www.zawya.com/en/business/uae-based-arada-to-co-develop-7bln-megaproject-in-syria-474965", ids:["arada"]},
];
window.SUGGESTED_EDGES = [];
