/* AUTO-GENERATED by tools/match_news.py — do not edit by hand. */
window.NEWS_ITEMS = [
  {id:"2026-09-03_h-m-sultan-haitham-mbs-discuss-regional-_ab3b4b", date:"2026-09-03", title:"H M Sultan Haitham, MBS discuss regional developments, de-escalation", source:"Muscat Daily", url:"https://www.muscatdaily.com/2026/09/01/h-m-sultan-haitham-mbs-discuss-regional-developments-de-escalation/", ids:["haitham"]},
];
window.SUGGESTED_EDGES = [];
