/* AUTO-GENERATED by tools/match_news.py — do not edit by hand. */
window.NEWS_ITEMS = [
  {id:"2026-09-03_lowest-bidder-emerges-for-sultan-haitham_7f7be2", date:"2026-09-03", title:"Lowest bidder emerges for Sultan Haitham City infrastructure", source:"MEED", url:"https://www.meed.com/lowest-bidder-emerges-for-sultan-haitham-city-infrastructure", ids:["haitham"]},
  {id:"2026-09-03_h-m-sultan-haitham-mbs-discuss-regional-_ab3b4b", date:"2026-09-03", title:"H M Sultan Haitham, MBS discuss regional developments, de-escalation", source:"Muscat Daily", url:"https://www.muscatdaily.com/2026/09/01/h-m-sultan-haitham-mbs-discuss-regional-developments-de-escalation/", ids:["haitham"]},
  {id:"2026-09-03_moody-s-affirms-omantel-s-ba1-rating-rai_986b38", date:"2026-09-03", title:"Moody’s affirms Omantel’s Ba1 rating, raises outlook to positive", source:"Muscat Daily", url:"https://www.muscatdaily.com/2026/09/01/moodys-affirms-omantels-ba1-rating-raises-outlook-to-positive/", ids:["omantel"]},
  {id:"2026-09-03_sohar-international-nbo-jointly-lead-720_035097", date:"2026-09-03", title:"Sohar International, NBO jointly lead $720mn refinancing for Phoenix Power", source:"Muscat Daily", url:"https://www.muscatdaily.com/2026/09/01/sohar-international-nbo-jointly-lead-720mn-refinancing-for-phoenix-power/", ids:["sohar_bank"]},
];
window.SUGGESTED_EDGES = [];
