"""Export the network database (network_data.js) to editable CSV tables in data/.

  python tools/export_csv.py

Produces: data/people.csv, data/roles.csv, data/institutions.csv,
data/ownership.csv, data/family.csv, data/aka.csv

Review/edit the CSVs, then run  python tools/import_csv.py  to regenerate
network_data.js. Columns ending in _name are informational only — the importer
matches on ids.
"""
import csv
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_JS = ROOT / "network_data.js"
OUT = ROOT / "data"

STR = r'"((?:[^"\\]|\\.)*)"'

def parse(text):
    """Full parse of network_data.js (handles both the original + L3-addendum shape
    and the flat shape regenerated by import_csv.py)."""
    insts, people = [], []

    # institutions: single-line entries  {id:"..", n:"..", s:"..", t:N, p:N, short:".."}
    for m in re.finditer(r'\{id:' + STR + r',\s*n:' + STR + r',\s*s:' + STR +
                         r',\s*t:(\d+),\s*p:(\d+)(?:,\s*short:' + STR + r')?\s*\}', text):
        insts.append({"id": m.group(1), "name": m.group(2), "sector": m.group(3),
                      "tier": int(m.group(4)), "power": int(m.group(5)), "short": m.group(6) or ""})

    # people: multi-line entries  {id:"..", n:"..", t:N, p:N, s:"..", roles:[...], note:".."}
    for m in re.finditer(r'\{id:' + STR + r',\s*n:' + STR + r',\s*t:(\d+),\s*p:(\d+),\s*s:' + STR +
                         r',\s*roles:\[(.*?)\]\s*(?:,\s*note:' + STR + r')?\s*\}', text, re.S):
        roles = re.findall(r'\[' + STR + r',' + STR + r',' + STR + r'(?:,' + STR + r')?(?:,' + STR + r')?\]', m.group(6))
        people.append({"id": m.group(1), "name": m.group(2), "tier": int(m.group(3)),
                       "power": int(m.group(4)), "sector": m.group(5),
                       "roles": [(r[0], r[1], r[2], r[3] or "v", r[4]) for r in roles],
                       "note": m.group(7) or ""})

    # extra roles added via  PEOPLE.find(p => p.id === "x").roles.push([...])
    for m in re.finditer(r'PEOPLE\.find\(p\s*=>\s*p\.id\s*===\s*' + STR + r'\)\.roles\.push\((\[.*?\])\);', text):
        pid, arr = m.group(1), m.group(2)
        r = re.findall(r'\[' + STR + r',' + STR + r',' + STR + r'(?:,' + STR + r')?(?:,' + STR + r')?\]', arr)
        for p in people:
            if p["id"] == pid:
                p["roles"].extend((x[0], x[1], x[2], x[3] or "v", x[4]) for x in r)

    def edge_entries(name):
        rows = []
        for bm in re.finditer(r'(?:const\s+' + name + r'\s*=\s*\[|' + name + r'\.push\()(.*?)(?:\];|\);)', text, re.S):
            for m in re.finditer(r'\[' + STR + r',' + STR + r'(?:,' + STR + r')?(?:,' + STR + r')?\]', bm.group(1)):
                rows.append((m.group(1), m.group(2), m.group(3) or "", m.group(4) or ""))
        return rows

    ownership = [(a, b, lbl, v or "v") for a, b, lbl, v in edge_entries("OWNERSHIP")]
    family = [(a, b, lbl) for a, b, lbl, _ in edge_entries("FAMILY")]

    aka = {}
    m = re.search(r'const AKA\s*=\s*\{(.*?)\n\};', text, re.S)
    if m:
        for em in re.finditer(r'(\w+)\s*:\s*\[([^\]]*)\]', m.group(1)):
            aka[em.group(1)] = re.findall(STR, em.group(2))

    # de-duplicate people that also matched the institution regex (none expected) and vice versa
    inst_ids = {i["id"] for i in insts}
    people = [p for p in people if p["id"] not in inst_ids]
    return insts, people, ownership, family, aka


def main():
    text = DATA_JS.read_text(encoding="utf-8")
    insts, people, ownership, family, aka = parse(text)
    OUT.mkdir(exist_ok=True)
    iname = {i["id"]: i["name"] for i in insts}
    pname = {p["id"]: p["name"] for p in people}

    def w(fname, header, rows):
        with open(OUT / fname, "w", newline="", encoding="utf-8-sig") as f:
            wr = csv.writer(f)
            wr.writerow(header)
            wr.writerows(rows)
        print(f"  data/{fname}: {len(rows)} rows")

    w("institutions.csv", ["id", "name", "short", "sector", "tier", "power"],
      [[i["id"], i["name"], i["short"], i["sector"], i["tier"], i["power"]] for i in insts])
    w("people.csv", ["id", "name", "tier", "power", "sector", "note"],
      [[p["id"], p["name"], p["tier"], p["power"], p["sector"], p["note"]] for p in people])
    w("roles.csv", ["person_id", "person_name", "institution_id", "institution_name",
                    "title", "role_type", "verification", "status"],
      [[p["id"], p["name"], r[0], iname.get(r[0], "?"), r[1], r[2], r[3], r[4] if len(r) > 4 else ""]
       for p in people for r in p["roles"]])
    w("ownership.csv", ["child_id", "child_name", "parent_id", "parent_name", "label", "verification"],
      [[a, iname.get(a, "?"), b, iname.get(b, "?"), lbl, v] for a, b, lbl, v in ownership])
    w("family.csv", ["person_a_id", "person_a_name", "person_b_id", "person_b_name", "relation"],
      [[a, pname.get(a, "?"), b, pname.get(b, "?"), lbl] for a, b, lbl in family])
    w("aka.csv", ["id", "aliases"],
      [[k, "|".join(v)] for k, v in aka.items()])

if __name__ == "__main__":
    main()
