"""LinkedIn connections → network overlay.

1. LinkedIn → Settings & Privacy → Data privacy → "Get a copy of your data"
   → tick "Connections" → download → unzip Connections.csv
2. Put Connections.csv in the project root (or pass a path as first argument).
3. Run:  python tools/import_linkedin.py

Writes my_network.js — loaded automatically by the map. Institutions where you
have contacts get a green dashed ring, and the contacts are listed in that
institution's detail panel.

PRIVACY: my_network.js contains your personal contacts. It stays on this
machine; don't share it alongside the map. The map works fine without it.
"""
import csv
import re
import sys
import datetime
from pathlib import Path
from netdata import ROOT, load_nodes, js_string

OUT = ROOT / "my_network.js"

SUFFIXES = re.compile(
    r"\b(llc|l\.l\.c\.?|pjsc|psc|plc|inc\.?|ltd\.?|limited|company|co\.?|group|holding|holdings|"
    r"international|corporation|corp\.?|fz-?llc|fze|dmcc)\b", re.I)

def norm(s):
    s = s.lower()
    s = re.sub(r"[^\w& ]+", " ", s)
    s = SUFFIXES.sub(" ", s)
    return re.sub(r"\s+", " ", s).strip()

def build_index(nodes):
    idx = []
    for n in nodes:
        if n["kind"] != "inst":
            continue
        for a in n["aliases"]:
            na = norm(a)
            if len(na) >= 3:
                idx.append((na, n["id"]))
    # longest aliases first so "adnoc gas" wins over "adnoc"
    idx.sort(key=lambda x: -len(x[0]))
    return idx

def match_company(company, idx):
    nc = norm(company)
    if not nc:
        return []
    hits = []
    for na, nid in idx:
        if nid in hits:
            continue
        if na == nc or (len(na) >= 4 and na in nc) or (len(nc) >= 4 and nc in na):
            hits.append(nid)
    return hits[:3]

def find_header(rows):
    for i, row in enumerate(rows[:10]):
        if any("first name" in (c or "").strip().lower() for c in row):
            return i
    return 0

def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "Connections.csv"
    if not src.exists():
        print(f"Connections.csv not found at {src}.\n"
              "Export it from LinkedIn (Settings -> Data privacy -> Get a copy of your data)\n"
              "and place it in the project root, or pass its path as an argument.")
        sys.exit(1)

    with open(src, encoding="utf-8-sig", newline="") as f:
        rows = list(csv.reader(f))
    h = find_header(rows)
    header = [c.strip().lower() for c in rows[h]]
    def col(name):
        return header.index(name) if name in header else None
    ci = {k: col(k) for k in ("first name", "last name", "company", "position")}

    nodes = load_nodes()
    idx = build_index(nodes)
    name_of = {n["id"]: n["short"] for n in nodes}

    contacts, matched = [], 0
    for row in rows[h + 1:]:
        if not row or all(not c.strip() for c in row):
            continue
        def get(k):
            i = ci.get(k)
            return row[i].strip() if i is not None and i < len(row) else ""
        full = (get("first name") + " " + get("last name")).strip()
        company, pos = get("company"), get("position")
        if not full:
            continue
        inst = match_company(company, idx)
        if inst:
            matched += 1
        contacts.append({"n": full, "company": company, "pos": pos, "inst": inst})

    lines = []
    for c in contacts:
        lines.append("  {n:%s, company:%s, pos:%s, inst:[%s]}," % (
            js_string(c["n"]), js_string(c["company"]), js_string(c["pos"]),
            ",".join(js_string(i) for i in c["inst"])))
    OUT.write_text(
        "/* AUTO-GENERATED by tools/import_linkedin.py — PRIVATE, do not share.\n"
        "   Generated " + datetime.date.today().isoformat() + " */\n"
        "window.MY_NETWORK = {generated:" + js_string(datetime.date.today().isoformat())
        + ", contacts:[\n" + "\n".join(lines) + "\n]};\n",
        encoding="utf-8")

    print(f"{len(contacts)} contacts read, {matched} matched to institutions -> {OUT.name}")
    by_inst = {}
    for c in contacts:
        for i in c["inst"]:
            by_inst[i] = by_inst.get(i, 0) + 1
    for i, cnt in sorted(by_inst.items(), key=lambda x: -x[1])[:20]:
        print(f"  {name_of.get(i, i)}: {cnt}")

if __name__ == "__main__":
    main()
