"""Regenerate network_data.js from the CSV tables in data/.

  python tools/import_csv.py

Reads data/{institutions,people,roles,ownership,family,aka}.csv, validates
cross-references, and rewrites network_data.js as clean flat arrays (the SECTORS
block is carried over from the current file). Refresh the map in the browser to
see the result; re-run tools/match_news.py afterwards so news aliases stay in sync.
"""
import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_JS = ROOT / "network_data.js"
D = ROOT / "data"

ROLE_TYPES = {"political", "government", "board", "executive", "ownership"}

def js(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'

def read(fname):
    with open(D / fname, encoding="utf-8-sig", newline="") as f:
        return [row for row in csv.DictReader(f) if any((v or "").strip() for v in row.values())]

def main():
    text = DATA_JS.read_text(encoding="utf-8")
    m = re.search(r'(const SECTORS = \{.*?\n\};)', text, re.S)
    if not m:
        sys.exit("could not find SECTORS block in network_data.js")
    sectors_block = m.group(1)
    # include any SECTORS.x = {...} additions (e.g. professional)
    sectors_block += "".join("\n" + a.group(0) for a in re.finditer(r'SECTORS\.\w+\s*=\s*\{[^}]*\};', text))
    sector_keys = set(re.findall(r'^\s*(\w+)\s*:\s*\{', sectors_block, re.M)) | \
                  set(re.findall(r'SECTORS\.(\w+)\s*=', sectors_block))

    insts = read("institutions.csv")
    people = read("people.csv")
    roles = read("roles.csv")
    ownership = read("ownership.csv")
    family = read("family.csv")
    aka = read("aka.csv")

    # ---- validation ----
    errors = []
    iids = {r["id"].strip() for r in insts}
    pids = {r["id"].strip() for r in people}
    dup = [x for x in iids & pids]
    if dup: errors.append(f"ids used for both a person and an institution: {dup}")
    for r in insts + people:
        if r["sector"].strip() not in sector_keys:
            errors.append(f"unknown sector '{r['sector']}' on {r['id']} (known: {sorted(sector_keys)})")
        if not r["tier"].strip().isdigit() or not (0 <= int(r["tier"]) <= 3):
            errors.append(f"tier must be 0-3 on {r['id']}")
        if not r["power"].strip().isdigit():
            errors.append(f"power must be a number on {r['id']}")
    for r in roles:
        if r["person_id"].strip() not in pids: errors.append(f"roles.csv: unknown person_id {r['person_id']}")
        if r["institution_id"].strip() not in iids: errors.append(f"roles.csv: unknown institution_id {r['institution_id']} (role of {r['person_id']})")
        if r["role_type"].strip() not in ROLE_TYPES: errors.append(f"roles.csv: bad role_type '{r['role_type']}' on {r['person_id']} (use {sorted(ROLE_TYPES)})")
        if r["verification"].strip() not in ("v", "ns"): errors.append(f"roles.csv: verification must be v or ns on {r['person_id']}/{r['institution_id']}")
    for r in ownership:
        for c in ("child_id", "parent_id"):
            if r[c].strip() not in iids: errors.append(f"ownership.csv: unknown {c} {r[c]}")
        if r["verification"].strip() not in ("v", "ns"): errors.append(f"ownership.csv: verification must be v or ns on {r['child_id']}")
    for r in family:
        for c in ("person_a_id", "person_b_id"):
            if r[c].strip() not in pids: errors.append(f"family.csv: unknown {c} {r[c]}")
    for r in aka:
        if r["id"].strip() not in pids | iids: errors.append(f"aka.csv: unknown id {r['id']}")
    if errors:
        print("IMPORT ABORTED — fix these first:")
        for e in errors: print("  -", e)
        sys.exit(1)

    # ---- generate ----
    roles_by = {}
    for r in roles:
        roles_by.setdefault(r["person_id"].strip(), []).append(r)

    out = ["/* ================================================================",
           "   ABU DHABI POWER NETWORK — DATASET",
           "   GENERATED by tools/import_csv.py from data/*.csv — edit the CSVs",
           "   (or edit here and run tools/export_csv.py to refresh the CSVs).",
           "   ================================================================ */",
           "", sectors_block, "", "const INSTITUTIONS = ["]
    for r in insts:
        out.append(f'  {{id:{js(r["id"].strip())}, n:{js(r["name"])}, s:{js(r["sector"].strip())}, '
                   f't:{int(r["tier"])}, p:{int(r["power"])}, short:{js(r["short"] or r["name"])}}},')
    out.append("];")
    out.append("")
    out.append("const PEOPLE = [")
    for r in people:
        pid = r["id"].strip()
        out.append(f'  {{id:{js(pid)}, n:{js(r["name"])}, t:{int(r["tier"])}, p:{int(r["power"])}, s:{js(r["sector"].strip())}, roles:[')
        for rr in roles_by.get(pid, []):
            out.append(f'    [{js(rr["institution_id"].strip())},{js(rr["title"])},{js(rr["role_type"].strip())},{js(rr["verification"].strip())}],')
        note = (r.get("note") or "").strip()
        out.append(f'    ], note:{js(note)}}},' if note else "    ]},")
    out.append("];")
    out.append("")
    out.append("const OWNERSHIP = [")
    for r in ownership:
        out.append(f'  [{js(r["child_id"].strip())},{js(r["parent_id"].strip())},{js(r["label"] or "")},{js(r["verification"].strip())}],')
    out.append("];")
    out.append("")
    out.append("const FAMILY = [")
    for r in family:
        out.append(f'  [{js(r["person_a_id"].strip())},{js(r["person_b_id"].strip())},{js(r["relation"] or "")}],')
    out.append("];")
    out.append("")
    out.append("const AKA = {")
    for r in aka:
        alts = [a.strip() for a in (r["aliases"] or "").split("|") if a.strip()]
        out.append(f'  {r["id"].strip()}:[{",".join(js(a) for a in alts)}],')
    out.append("};")
    out.append("")

    DATA_JS.write_text("\n".join(out), encoding="utf-8")
    print(f"network_data.js regenerated: {len(insts)} institutions, {len(people)} people, "
          f"{len(roles)} roles, {len(ownership)} ownership, {len(family)} family, {len(aka)} aka")

if __name__ == "__main__":
    main()
