"""News → network matcher.

Drop news items into news_inbox/ as .txt or .md files:
  - filename may start with a date:  2026-08-25_adnoc-deal.md  (else file date is used)
  - first non-empty line = title (a leading '# ' is stripped)
  - optional metadata lines anywhere in the first 10 lines:
        source: Reuters
        url: https://...
  - rest = body

Run:  python tools/match_news.py

The script scans every item against all node names + aliases from network_data.js
and regenerates news_data.js (idempotent — safe to re-run any time).
Matched nodes get a gold signal badge on the map and a "Recent signals" section
in their detail panel.
"""
import re
import datetime
from pathlib import Path
from netdata import ROOT, load_nodes, js_string

INBOX = ROOT / "news_inbox"
OUT = ROOT / "news_data.js"

# aliases that are too generic to match on their own
STOP_ALIASES = {"bp", "eni", "ey", "shell", "e&", "doe", "dof", "doh", "dmt", "dge", "dcd"}

def alias_patterns(nodes):
    pats = []
    for n in nodes:
        for a in n["aliases"]:
            if len(a) < 3 and a.lower() not in {"bp", "ey", "e&"}:
                continue
            # allow line breaks / multiple spaces inside multi-word names
            body = r"\s+".join(re.escape(w) for w in a.split())
            if a.isupper() or a.lower() in STOP_ALIASES:
                # abbreviations: exact-case, word-boundary match
                pat = re.compile(r"\b" + body + r"\b")
            else:
                pat = re.compile(r"\b" + body + r"\b", re.I)
            pats.append((pat, n["id"], a))
    return pats

def parse_item(path: Path):
    text = path.read_text(encoding="utf-8", errors="replace")
    lines = [l.rstrip() for l in text.splitlines()]
    title, source, url = None, "", ""
    for l in lines[:10]:
        low = l.lower()
        if low.startswith("source:"):
            source = l.split(":", 1)[1].strip()
        elif low.startswith("url:"):
            url = l.split(":", 1)[1].strip()
        elif title is None and l.strip():
            title = l.strip().lstrip("# ").strip()
    m = re.match(r"(\d{4}-\d{2}-\d{2})", path.stem)
    date = m.group(1) if m else datetime.date.fromtimestamp(path.stat().st_mtime).isoformat()
    return {"id": path.stem, "date": date, "title": title or path.stem,
            "source": source, "url": url, "text": text}

def main():
    nodes = load_nodes()
    pats = alias_patterns(nodes)
    INBOX.mkdir(exist_ok=True)
    files = sorted([p for p in INBOX.iterdir() if p.suffix.lower() in (".txt", ".md")])
    items = []
    for f in files:
        it = parse_item(f)
        hits = {}
        for pat, nid, alias in pats:
            if nid in hits:
                continue
            if pat.search(it["text"]):
                hits[nid] = alias
        # drop a match whose alias is just a fragment of another matched alias
        # (e.g. "Al Jaber" group vs "Sultan Al Jaber" the person)
        drop = set()
        for nid, alias in hits.items():
            for nid2, alias2 in hits.items():
                if nid != nid2 and alias.lower() != alias2.lower() and alias.lower() in alias2.lower():
                    drop.add(nid)
        for nid in drop:
            del hits[nid]
        it["ids"] = sorted(hits)
        items.append(it)
        tag = ", ".join(hits[k] for k in sorted(hits)) if hits else "NO MATCH"
        print(f"  {f.name}: {len(hits)} matched  [{tag}]")

    items.sort(key=lambda x: x["date"], reverse=True)
    rows = []
    for it in items:
        rows.append("  {id:%s, date:%s, title:%s, source:%s, url:%s, ids:[%s]}," % (
            js_string(it["id"]), js_string(it["date"]), js_string(it["title"]),
            js_string(it["source"]), js_string(it["url"]),
            ",".join(js_string(i) for i in it["ids"])))
    OUT.write_text(
        "/* AUTO-GENERATED by tools/match_news.py — do not edit by hand.\n"
        "   Re-run the script after adding files to news_inbox/. */\n"
        "window.NEWS_ITEMS = [\n" + "\n".join(rows) + "\n];\n",
        encoding="utf-8")
    print(f"\n{len(items)} items -> {OUT.name} "
          f"({sum(1 for i in items if i['ids'])} matched at least one node)")

if __name__ == "__main__":
    main()
