/* ================================================================
   ABU DHABI POWER NETWORK — DATASET
   GENERATED by tools/import_csv.py from data/*.csv — edit the CSVs
   (or edit here and run tools/export_csv.py to refresh the CSVs).
   ================================================================ */

const SECTORS = {
  // ---- GICS 11 ----
  energy:       {name:"Energy",                 color:"#f2703e"},
  materials:    {name:"Materials",              color:"#b08968"},
  industry:     {name:"Industrials",            color:"#c98a5e"},
  consumer_disc:{name:"Consumer Discretionary", color:"#ef7fb1"},
  consumer_stap:{name:"Consumer Staples",       color:"#9ccc65"},
  health:       {name:"Health Care",            color:"#35b8a4"},
  finance:      {name:"Financials",             color:"#3ecf8e"},
  tech:         {name:"Information Technology", color:"#a06ef5"},
  comm:         {name:"Communication Services", color:"#7e57c2"},
  utilities:    {name:"Utilities",              color:"#f5a623"},
  realestate:   {name:"Real Estate",            color:"#58c4dd"},
  // ---- government-side sectors (a power map needs these) ----
  gov:          {name:"Government & Political", color:"#5b8def"},
  sovereign:    {name:"Sovereign Capital",      color:"#e8b64c"},
  education:    {name:"Education & Research",   color:"#8bc34a"},
  conglomerate: {name:"Family Conglomerates",   color:"#b0a08a"},
};

const INSTITUTIONS = [
  {id:"adgov", n:"Abu Dhabi Government (Ruler's Court)", s:"gov", t:0, p:100, short:"AD Govt"},
  {id:"prescourt", n:"UAE Presidential Court", s:"gov", t:0, p:95, short:"Pres. Court"},
  {id:"fedgov", n:"UAE Cabinet / Federal Government", s:"gov", t:0, p:92, short:"UAE Cabinet"},
  {id:"execcouncil", n:"Abu Dhabi Executive Council", s:"gov", t:0, p:96, short:"Exec Council"},
  {id:"scfea", n:"Supreme Council for Financial & Economic Affairs", s:"gov", t:0, p:95, short:"SCFEA"},
  {id:"eaa", n:"Executive Affairs Authority", s:"gov", t:1, p:82, short:"EAA"},
  {id:"dof", n:"Department of Finance", s:"gov", t:1, p:88, short:"DoF"},
  {id:"added", n:"Department of Economic Development", s:"gov", t:1, p:85, short:"ADDED"},
  {id:"doe", n:"Department of Energy", s:"gov", t:1, p:82, short:"DoE"},
  {id:"doh", n:"Department of Health", s:"gov", t:1, p:82, short:"DoH"},
  {id:"dmt", n:"Department of Municipalities & Transport", s:"gov", t:1, p:83, short:"DMT"},
  {id:"dge", n:"Department of Government Enablement", s:"gov", t:1, p:78, short:"DGE"},
  {id:"adek", n:"Department of Education & Knowledge", s:"gov", t:1, p:78, short:"ADEK"},
  {id:"dct", n:"Department of Culture & Tourism", s:"gov", t:1, p:80, short:"DCT"},
  {id:"dcd", n:"Department of Community Development", s:"gov", t:1, p:72, short:"DCD"},
  {id:"ead", n:"Environment Agency – Abu Dhabi", s:"gov", t:1, p:76, short:"EAD"},
  {id:"adafsa", n:"Abu Dhabi Agriculture & Food Safety Authority", s:"gov", t:2, p:66, short:"ADAFSA"},
  {id:"adio", n:"Abu Dhabi Investment Office", s:"gov", t:1, p:76, short:"ADIO"},
  {id:"admo", n:"Abu Dhabi Media Office", s:"comm", t:1, p:72, short:"AD Media Office"},
  {id:"mofa", n:"UAE Ministry of Foreign Affairs", s:"gov", t:1, p:84, short:"MoFA"},
  {id:"cbuae", n:"Central Bank of the UAE", s:"finance", t:1, p:86, short:"CBUAE"},
  {id:"sca", n:"Securities & Commodities Authority", s:"finance", t:2, p:70, short:"SCA"},
  {id:"spaceagency", n:"UAE Space Agency", s:"tech", t:2, p:70, short:"Space Agency"},
  {id:"tawazun", n:"Tawazun Council", s:"gov", t:1, p:76, short:"Tawazun"},
  {id:"atrc", n:"Advanced Technology Research Council", s:"tech", t:1, p:76, short:"ATRC"},
  {id:"adia", n:"Abu Dhabi Investment Authority", s:"sovereign", t:1, p:97, short:"ADIA"},
  {id:"mubadala", n:"Mubadala Investment Company", s:"sovereign", t:1, p:96, short:"Mubadala"},
  {id:"adq", n:"ADQ", s:"sovereign", t:1, p:94, short:"ADQ"},
  {id:"ihc", n:"International Holding Company", s:"sovereign", t:1, p:92, short:"IHC"},
  {id:"royalgroup", n:"Royal Group", s:"sovereign", t:1, p:88, short:"Royal Group"},
  {id:"chimera", n:"Chimera Investments", s:"sovereign", t:2, p:78, short:"Chimera"},
  {id:"lunate", n:"Lunate", s:"sovereign", t:2, p:76, short:"Lunate"},
  {id:"mgx", n:"MGX", s:"sovereign", t:1, p:84, short:"MGX"},
  {id:"twopointzero", n:"2PointZero", s:"sovereign", t:2, p:74, short:"2PointZero"},
  {id:"alphadhabi", n:"Alpha Dhabi Holding", s:"sovereign", t:2, p:80, short:"Alpha Dhabi"},
  {id:"multiply", n:"Multiply Group", s:"sovereign", t:2, p:72, short:"Multiply"},
  {id:"eia", n:"Emirates Investment Authority", s:"sovereign", t:1, p:80, short:"EIA"},
  {id:"hub71", n:"Hub71", s:"tech", t:2, p:68, short:"Hub71"},
  {id:"adnoc", n:"ADNOC Group", s:"energy", t:1, p:97, short:"ADNOC"},
  {id:"xrg", n:"XRG (ADNOC international investment)", s:"energy", t:2, p:80, short:"XRG"},
  {id:"adnocgas", n:"ADNOC Gas", s:"energy", t:2, p:78, short:"ADNOC Gas"},
  {id:"adnocdrill", n:"ADNOC Drilling", s:"energy", t:2, p:72, short:"ADNOC Drilling"},
  {id:"adnocls", n:"ADNOC Logistics & Services", s:"energy", t:2, p:70, short:"ADNOC L&S"},
  {id:"adnocdist", n:"ADNOC Distribution", s:"energy", t:2, p:72, short:"ADNOC Dist."},
  {id:"borouge", n:"Borouge", s:"materials", t:2, p:74, short:"Borouge"},
  {id:"fertiglobe", n:"Fertiglobe", s:"materials", t:2, p:68, short:"Fertiglobe"},
  {id:"masdar", n:"Masdar", s:"utilities", t:1, p:82, short:"Masdar"},
  {id:"taqa", n:"TAQA Group", s:"utilities", t:1, p:86, short:"TAQA"},
  {id:"ewec", n:"Emirates Water & Electricity Company", s:"utilities", t:2, p:78, short:"EWEC"},
  {id:"enec", n:"Emirates Nuclear Energy Company (Barakah)", s:"utilities", t:1, p:80, short:"ENEC"},
  {id:"fab", n:"First Abu Dhabi Bank", s:"finance", t:1, p:88, short:"FAB"},
  {id:"adcb", n:"Abu Dhabi Commercial Bank", s:"finance", t:1, p:82, short:"ADCB"},
  {id:"adib", n:"Abu Dhabi Islamic Bank", s:"finance", t:2, p:76, short:"ADIB"},
  {id:"wio", n:"Wio Bank", s:"finance", t:2, p:62, short:"Wio"},
  {id:"adx", n:"Abu Dhabi Securities Exchange", s:"finance", t:2, p:72, short:"ADX"},
  {id:"adgm", n:"Abu Dhabi Global Market", s:"finance", t:1, p:84, short:"ADGM"},
  {id:"g42", n:"G42", s:"tech", t:1, p:90, short:"G42"},
  {id:"core42", n:"Core42", s:"tech", t:2, p:72, short:"Core42"},
  {id:"presight", n:"Presight AI", s:"tech", t:2, p:70, short:"Presight"},
  {id:"space42", n:"Space42", s:"tech", t:2, p:74, short:"Space42"},
  {id:"khazna", n:"Khazna Data Centers", s:"tech", t:2, p:70, short:"Khazna"},
  {id:"mbzuai", n:"Mohamed bin Zayed University of AI", s:"education", t:2, p:72, short:"MBZUAI"},
  {id:"e_and", n:"e& (Etisalat Group)", s:"comm", t:1, p:84, short:"e&"},
  {id:"tii", n:"Technology Innovation Institute", s:"tech", t:2, p:66, short:"TII"},
  {id:"edge_grp", n:"EDGE Group", s:"industry", t:1, p:84, short:"EDGE"},
  {id:"calidus", n:"Calidus Holding", s:"industry", t:2, p:60, short:"Calidus"},
  {id:"purehealth", n:"PureHealth", s:"health", t:1, p:80, short:"PureHealth"},
  {id:"seha", n:"SEHA (AD Health Services)", s:"health", t:2, p:66, short:"SEHA"},
  {id:"daman", n:"Daman (National Health Insurance)", s:"health", t:2, p:62, short:"Daman"},
  {id:"m42", n:"M42", s:"health", t:2, p:74, short:"M42"},
  {id:"ccad", n:"Cleveland Clinic Abu Dhabi", s:"health", t:2, p:64, short:"CCAD"},
  {id:"burjeel", n:"Burjeel Holdings", s:"health", t:2, p:68, short:"Burjeel"},
  {id:"aldar", n:"Aldar Properties", s:"realestate", t:1, p:82, short:"Aldar"},
  {id:"modon", n:"Modon Holding", s:"realestate", t:2, p:74, short:"Modon"},
  {id:"adnh", n:"Abu Dhabi National Hotels", s:"realestate", t:2, p:60, short:"ADNH"},
  {id:"adports", n:"AD Ports Group", s:"industry", t:1, p:82, short:"AD Ports"},
  {id:"etihad", n:"Etihad Airways", s:"industry", t:1, p:80, short:"Etihad"},
  {id:"adairports", n:"Abu Dhabi Airports", s:"industry", t:2, p:72, short:"AD Airports"},
  {id:"etihadrail", n:"Etihad Rail", s:"industry", t:2, p:74, short:"Etihad Rail"},
  {id:"itc", n:"Integrated Transport Centre", s:"gov", t:2, p:62, short:"ITC"},
  {id:"ega", n:"Emirates Global Aluminium", s:"materials", t:1, p:78, short:"EGA"},
  {id:"emsteel", n:"EMSTEEL (Emirates Steel Arkan)", s:"materials", t:2, p:70, short:"EMSTEEL"},
  {id:"strata", n:"Strata Manufacturing", s:"industry", t:2, p:62, short:"Strata"},
  {id:"nmdc", n:"NMDC Group", s:"industry", t:2, p:68, short:"NMDC"},
  {id:"agthia", n:"Agthia Group", s:"consumer_stap", t:2, p:66, short:"Agthia"},
  {id:"silal", n:"Silal", s:"consumer_stap", t:2, p:60, short:"Silal"},
  {id:"aldahra", n:"Al Dahra Holding", s:"consumer_stap", t:2, p:62, short:"Al Dahra"},
  {id:"lulu", n:"LuLu Group International", s:"consumer_stap", t:2, p:72, short:"LuLu"},
  {id:"miral", n:"Miral (Yas Island / destinations)", s:"consumer_disc", t:2, p:76, short:"Miral"},
  {id:"adnec", n:"ADNEC Group", s:"consumer_disc", t:2, p:70, short:"ADNEC"},
  {id:"louvre", n:"Louvre Abu Dhabi", s:"consumer_disc", t:2, p:62, short:"Louvre AD"},
  {id:"flash", n:"Flash Entertainment", s:"comm", t:2, p:58, short:"Flash"},
  {id:"cfg", n:"City Football Group / Manchester City", s:"comm", t:2, p:72, short:"CFG"},
  {id:"imi", n:"International Media Investments", s:"comm", t:2, p:72, short:"IMI"},
  {id:"skynewsarabia", n:"Sky News Arabia", s:"comm", t:2, p:60, short:"Sky News Arabia"},
  {id:"thenational", n:"The National", s:"comm", t:2, p:58, short:"The National"},
  {id:"khalifa_u", n:"Khalifa University", s:"education", t:2, p:68, short:"Khalifa Uni"},
  {id:"nyuad", n:"NYU Abu Dhabi", s:"education", t:2, p:66, short:"NYUAD"},
  {id:"sorbonne", n:"Sorbonne University Abu Dhabi", s:"education", t:2, p:58, short:"Sorbonne AD"},
  {id:"zayed_u", n:"Zayed University", s:"education", t:2, p:60, short:"Zayed Uni"},
  {id:"uaeu", n:"United Arab Emirates University", s:"education", t:2, p:64, short:"UAEU"},
  {id:"tadweer", n:"Tadweer Group", s:"industry", t:2, p:64, short:"Tadweer"},
  {id:"alnowais", n:"Al Nowais Investments", s:"conglomerate", t:2, p:62, short:"Al Nowais Inv."},
  {id:"almasaood", n:"Al Masaood Group", s:"conglomerate", t:2, p:62, short:"Al Masaood"},
  {id:"alfahim", n:"Al Fahim Group", s:"conglomerate", t:2, p:60, short:"Al Fahim"},
  {id:"binhamoodah", n:"Bin Hamoodah Group", s:"conglomerate", t:2, p:56, short:"Bin Hamoodah"},
  {id:"dasholding", n:"Das Holding", s:"conglomerate", t:2, p:58, short:"Das Holding"},
  {id:"aljaber", n:"Al Jaber Group", s:"conglomerate", t:2, p:60, short:"Al Jaber"},
  {id:"nationalholding", n:"National Holding", s:"conglomerate", t:2, p:62, short:"National Holding"},
  {id:"microsoft", n:"Microsoft", s:"tech", t:3, p:80, short:"Microsoft"},
  {id:"openai", n:"OpenAI", s:"tech", t:3, p:74, short:"OpenAI"},
  {id:"nvidia", n:"NVIDIA", s:"tech", t:3, p:74, short:"NVIDIA"},
  {id:"cerebras", n:"Cerebras Systems", s:"tech", t:3, p:60, short:"Cerebras"},
  {id:"huawei", n:"Huawei UAE", s:"tech", t:3, p:56, short:"Huawei"},
  {id:"totalenergies", n:"TotalEnergies", s:"energy", t:3, p:72, short:"TotalEnergies"},
  {id:"bp", n:"bp", s:"energy", t:3, p:70, short:"bp"},
  {id:"shell", n:"Shell", s:"energy", t:3, p:70, short:"Shell"},
  {id:"exxonmobil", n:"ExxonMobil", s:"energy", t:3, p:70, short:"ExxonMobil"},
  {id:"eni", n:"Eni", s:"energy", t:3, p:64, short:"Eni"},
  {id:"omv", n:"OMV", s:"energy", t:3, p:62, short:"OMV"},
  {id:"oxy", n:"Occidental Petroleum", s:"energy", t:3, p:60, short:"Occidental"},
  {id:"inpex", n:"INPEX (JODCO)", s:"energy", t:3, p:56, short:"INPEX"},
  {id:"cnpc", n:"CNPC", s:"energy", t:3, p:58, short:"CNPC"},
  {id:"kepco", n:"KEPCO", s:"utilities", t:3, p:58, short:"KEPCO"},
  {id:"blackrock", n:"BlackRock", s:"finance", t:3, p:76, short:"BlackRock"},
  {id:"goldman", n:"Goldman Sachs", s:"finance", t:3, p:66, short:"Goldman Sachs"},
  {id:"moelis", n:"Moelis & Company", s:"finance", t:3, p:62, short:"Moelis"},
  {id:"rothschildco", n:"Rothschild & Co", s:"finance", t:3, p:60, short:"Rothschild & Co"},
  {id:"waha", n:"Waha Capital", s:"finance", t:3, p:62, short:"Waha Capital"},
  {id:"adnic", n:"Abu Dhabi National Insurance Company", s:"finance", t:3, p:54, short:"ADNIC"},
  {id:"trojan", n:"Trojan Holding", s:"industry", t:3, p:60, short:"Trojan"},
  {id:"alisons", n:"Ali & Sons Holding", s:"conglomerate", t:3, p:58, short:"Ali & Sons"},
  {id:"rotana", n:"Rotana Hotels", s:"consumer_disc", t:3, p:62, short:"Rotana"},
  {id:"mckinsey", n:"McKinsey & Company", s:"industry", t:3, p:64, short:"McKinsey"},
  {id:"bcg", n:"Boston Consulting Group", s:"industry", t:3, p:60, short:"BCG"},
  {id:"pwc", n:"PwC Middle East", s:"industry", t:3, p:58, short:"PwC"},
  {id:"ey", n:"EY MENA", s:"industry", t:3, p:56, short:"EY"},
  {id:"kpmg", n:"KPMG Lower Gulf", s:"industry", t:3, p:54, short:"KPMG"},
  {id:"deloitte", n:"Deloitte Middle East", s:"industry", t:3, p:56, short:"Deloitte"},
  {id:"accenture", n:"Accenture Middle East", s:"industry", t:3, p:56, short:"Accenture"},
  {id:"altamimi", n:"Al Tamimi & Company", s:"industry", t:3, p:58, short:"Al Tamimi"},
  {id:"cliffordchance", n:"Clifford Chance", s:"industry", t:3, p:52, short:"Clifford Chance"},
  {id:"raytheon_em", n:"Raytheon Emirates", s:"industry", t:3, p:58, short:"Raytheon Emirates"},
  {id:"lst_eand", n:"Emirates Telecommunications Group Company PJSC", s:"comm", t:2, p:50, short:"EAND"},
  {id:"lst_ords", n:"Ooredoo Q.P.S.C.", s:"comm", t:2, p:50, short:"Ooredoo Q.P.S.C."},
  {id:"lst_adports", n:"Abu Dhabi Ports Company PJSC", s:"industry", t:2, p:50, short:"ADPORTS"},
  {id:"lst_mbme", n:"MBME Group PJSC", s:"health", t:2, p:50, short:"MBME Group PJSC"},
  {id:"lst_purehealth", n:"Pure Health Holding PJSC", s:"health", t:2, p:50, short:"PUREHEALTH"},
  {id:"lst_2pointzero", n:"Two Point Zero Group PJSC", s:"tech", t:2, p:50, short:"2POINTZERO"},
  {id:"lst_agility", n:"Agility Global PLC", s:"industry", t:2, p:50, short:"Agility Global PLC"},
  {id:"lst_apex", n:"Apex Investment PSC", s:"finance", t:2, p:50, short:"Apex Investment PSC"},
  {id:"lst_sib", n:"Sharjah Islamic Bank PJSC", s:"finance", t:2, p:50, short:"SIB"},
  {id:"lst_inb", n:"Invest Bank P.S.C.", s:"finance", t:2, p:50, short:"Invest Bank P.S.C."},
  {id:"lst_alefedt", n:"Alef Education Holding plc", s:"consumer_disc", t:2, p:50, short:"ALEFEDT"},
  {id:"lst_oras", n:"Orascom Construction PLC", s:"industry", t:2, p:50, short:"ORAS"},
  {id:"lst_dana", n:"Dana Gas PJSC", s:"energy", t:2, p:50, short:"Dana Gas PJSC"},
  {id:"lst_adaviation", n:"Abu Dhabi Aviation Company", s:"industry", t:2, p:50, short:"ADAVIATION"},
  {id:"lst_bos", n:"Bank of Sharjah PJSC", s:"finance", t:2, p:50, short:"Bank of Sharjah PJSC"},
  {id:"lst_uab", n:"United Arab Bank PJSC", s:"finance", t:2, p:50, short:"UAB"},
  {id:"lst_emobility", n:"Emirates Mobility Company PJSC", s:"industry", t:2, p:50, short:"EMOBILITY"},
  {id:"lst_icap", n:"Investcorp Capital plc", s:"finance", t:2, p:50, short:"ICAP"},
  {id:"lst_phx", n:"Phoenix Group PLC", s:"tech", t:2, p:50, short:"Phoenix Group PLC"},
  {id:"lst_gih", n:"Gulf Investment House K.P.S.C.", s:"finance", t:2, p:50, short:"GIH"},
  {id:"lst_rakprop", n:"RAK Properties PJSC", s:"realestate", t:2, p:50, short:"RAK Properties PJSC"},
  {id:"lst_saga", n:"Sagasse Investment Company Plc", s:"finance", t:2, p:50, short:"SAGA"},
  {id:"lst_anan", n:"Anan Investment Holding PJSC", s:"finance", t:2, p:50, short:"ANAN"},
  {id:"lst_esg", n:"ESG Emirates Stallions Group PJSC", s:"materials", t:2, p:50, short:"ESG"},
  {id:"lst_asm", n:"Al Seer Marine Supplies and Equipment Company PJSC", s:"industry", t:2, p:50, short:"ASM"},
  {id:"lst_ghitha", n:"Ghitha Holding PJSC", s:"consumer_stap", t:2, p:50, short:"Ghitha Holding PJSC"},
  {id:"lst_rakcec", n:"RAK Ceramics PJSC", s:"materials", t:2, p:50, short:"RAK Ceramics PJSC"},
  {id:"lst_mair", n:"MAIR Group PJSC", s:"consumer_stap", t:2, p:50, short:"MAIR Group PJSC"},
  {id:"lst_invictus", n:"Invictus Investment Company PLC", s:"finance", t:2, p:50, short:"INVICTUS"},
  {id:"lst_e7", n:"E7 Group PJSC", s:"industry", t:2, p:50, short:"E7 Group PJSC"},
  {id:"lst_eshraq", n:"Eshraq Investments PJSC", s:"realestate", t:2, p:50, short:"ESHRAQ"},
  {id:"lst_adsb", n:"Abu Dhabi Ship Building PJSC", s:"industry", t:2, p:50, short:"ADSB"},
  {id:"lst_gmpc", n:"Gulf Medical Projects Company PJSC", s:"health", t:2, p:50, short:"GMPC"},
  {id:"lst_alphadata", n:"Alpha Data PJSC", s:"tech", t:2, p:50, short:"Alpha Data PJSC"},
  {id:"lst_eic", n:"Emirates Insurance Company PJSC", s:"finance", t:2, p:50, short:"EIC"},
  {id:"lst_palms", n:"Palms Sports PJSC", s:"consumer_disc", t:2, p:50, short:"Palms Sports PJSC"},
  {id:"lst_julphar", n:"Gulf Pharmaceutical Industries P.S.C.", s:"health", t:2, p:50, short:"JULPHAR"},
  {id:"lst_dhafra", n:"Al Dhafra Insurance Company P.S.C.", s:"finance", t:2, p:50, short:"DHAFRA"},
  {id:"lst_scidc", n:"Sharjah Cement and Industrial Development Co. PJSC", s:"materials", t:2, p:50, short:"SCIDC"},
  {id:"lst_manazel", n:"Manazel PJSC", s:"realestate", t:2, p:50, short:"Manazel PJSC"},
  {id:"lst_sudatel", n:"Sudatel Telecom Group Limited", s:"comm", t:2, p:50, short:"SUDATEL"},
  {id:"lst_qic", n:"Umm Al Qaiwain General Investments Company P.S.C.", s:"finance", t:2, p:50, short:"QIC"},
  {id:"lst_easylease", n:"Easy Lease Motor Cycle Rental P.S.C.", s:"industry", t:2, p:50, short:"EASYLEASE"},
  {id:"lst_fh", n:"Finance House PJSC", s:"finance", t:2, p:50, short:"Finance House PJSC"},
  {id:"lst_rakwct", n:"Ras Al Khaimah Co. for White Cement & Construction Materials P.S.C.", s:"materials", t:2, p:50, short:"RAKWCT"},
  {id:"lst_kico", n:"Al Khaleej Investment PJSC", s:"finance", t:2, p:50, short:"KICO"},
  {id:"lst_alain", n:"Al Ain Ahlia Insurance Company P.S.C.", s:"finance", t:2, p:50, short:"ALAIN"},
  {id:"lst_gcem", n:"Gulf Cement Company P.S.C.", s:"materials", t:2, p:50, short:"GCEM"},
  {id:"lst_fbi", n:"Fujairah Building Industries PJSC", s:"materials", t:2, p:50, short:"FBI"},
  {id:"lst_rpm", n:"Response Plus Holding PJSC", s:"health", t:2, p:50, short:"RPM"},
  {id:"lst_sawaeed", n:"Sawaeed Holding PJSC", s:"industry", t:2, p:50, short:"Sawaeed Holding PJSC"},
  {id:"lst_union", n:"Union Insurance Company PJSC", s:"finance", t:2, p:50, short:"UNION"},
  {id:"lst_hh", n:"Hily Holding PJSC", s:"conglomerate", t:2, p:50, short:"Hily Holding PJSC"},
  {id:"lst_fidelityunited", n:"United Fidelity Insurance Company P.S.C.", s:"finance", t:2, p:50, short:"FIDELITYUNITED"},
  {id:"lst_hayah", n:"Hayah Insurance Company PJSC", s:"finance", t:2, p:50, short:"HAYAH"},
  {id:"lst_sico", n:"Sharjah Insurance Company P.S.C.", s:"finance", t:2, p:50, short:"SICO"},
  {id:"lst_rapco", n:"RAPCO Investment PJSC", s:"consumer_stap", t:2, p:50, short:"RAPCO"},
  {id:"lst_aram", n:"ARAM Group Company PJSC", s:"realestate", t:2, p:50, short:"ARAM"},
  {id:"lst_fci", n:"Fujairah Cement Industries PJSC", s:"materials", t:2, p:50, short:"FCI"},
  {id:"lst_oeihc", n:"Oman & Emirates Investment Holding Company SAOG", s:"finance", t:2, p:50, short:"OEIHC"},
  {id:"lst_ih", n:"Insurance House PJSC", s:"finance", t:2, p:50, short:"Insurance House PJSC"},
  {id:"lst_methaq", n:"Methaq Takaful Insurance P.S.C.", s:"finance", t:2, p:50, short:"METHAQ"},
];

const PEOPLE = [
  {id:"mbz", n:"H.H. Sheikh Mohamed bin Zayed Al Nahyan", t:0, p:100, s:"gov", roles:[
    ["adgov","President of the UAE · Ruler of Abu Dhabi","political","v"],
    ["scfea","Chairman","political","v"],
    ["mubadala","Chairman","board","v"],
    ], note:"Apex of the network. Ultimate authority over Abu Dhabi's sovereign capital and strategic direction."},
  {id:"khaled", n:"H.H. Sheikh Khaled bin Mohamed bin Zayed Al Nahyan", t:0, p:98, s:"gov", roles:[
    ["adgov","Crown Prince of Abu Dhabi","political","v"],
    ["execcouncil","Chairman","political","v"],
    ], note:"Son of MBZ. Runs the day-to-day machinery of Abu Dhabi government via the Executive Council."},
  {id:"tahnoun", n:"H.H. Sheikh Tahnoon bin Zayed Al Nahyan", t:0, p:99, s:"sovereign", roles:[
    ["adgov","Deputy Ruler of Abu Dhabi","political","v"],
    ["fedgov","UAE National Security Advisor","political","v"],
    ["adia","Chairman","board","v"],
    ["adq","Chairman","board","v"],
    ["fab","Chairman","board","v"],
    ["ihc","Chairman","board","v"],
    ["royalgroup","Chairman","board","v"],
    ["g42","Chairman","board","v"],
    ["mgx","Chairman","board","v"],
    ], note:"The single most connected node in Abu Dhabi business: security portfolio plus chairmanship of both giant SWFs and the IHC/G42/Royal Group commercial empire."},
  {id:"mansour", n:"H.H. Sheikh Mansour bin Zayed Al Nahyan", t:0, p:97, s:"gov", roles:[
    ["fedgov","Vice President · Deputy Prime Minister","political","v"],
    ["prescourt","Minister of the Presidential Court","political","v"],
    ["cbuae","Chairman of the Board","board","v"],
    ["eia","Chairman","board","v"],
    ["cfg","Owner","ownership","v"],
    ["imi","Owner","ownership","v"],
    ], note:"Controls the Presidential Court, federal financial levers, and the highest-profile sports/media holdings."},
  {id:"hazza", n:"H.H. Sheikh Hazza bin Zayed Al Nahyan", t:0, p:90, s:"gov", roles:[
    ["adgov","Deputy Ruler of Abu Dhabi","political","v"],
    ]},
  {id:"abdullah_bz", n:"H.H. Sheikh Abdullah bin Zayed Al Nahyan", t:0, p:92, s:"gov", roles:[
    ["fedgov","Deputy Prime Minister","political","v"],
    ["mofa","Minister of Foreign Affairs","political","v"],
    ]},
  {id:"saif_bz", n:"H.H. Sheikh Saif bin Zayed Al Nahyan", t:0, p:91, s:"gov", roles:[
    ["fedgov","Deputy Prime Minister · Minister of Interior","political","v"],
    ]},
  {id:"hamdan_bz", n:"H.H. Sheikh Hamdan bin Zayed Al Nahyan", t:0, p:88, s:"gov", roles:[
    ["adgov","Ruler's Representative, Al Dhafra Region","political","v"],
    ["ead","Chairman","board","v"],
    ]},
  {id:"hamed_bz", n:"H.H. Sheikh Hamed bin Zayed Al Nahyan", t:0, p:93, s:"sovereign", roles:[
    ["adia","Managing Director","executive","v"],
    ["execcouncil","Member","political","v"],
    ]},
  {id:"theyab", n:"H.H. Sheikh Theyab bin Mohamed bin Zayed Al Nahyan", t:0, p:91, s:"gov", roles:[
    ["prescourt","Deputy Chairman (Development & Fallen Heroes' Affairs)","political","v"],
    ["etihadrail","Chairman","board","v"],
    ]},
  {id:"nahyan_bm", n:"H.H. Sheikh Nahyan bin Mubarak Al Nahyan", t:0, p:80, s:"gov", roles:[
    ["fedgov","Minister of Tolerance & Coexistence","political","v"],
    ]},
  {id:"shakhbout_bn", n:"H.H. Sheikh Shakhbout bin Nahyan Al Nahyan", t:0, p:74, s:"gov", roles:[
    ["fedgov","Minister of State","political","v"],
    ]},
  {id:"khaldoon", n:"Khaldoon Khalifa Al Mubarak", t:1, p:96, s:"sovereign", roles:[
    ["mubadala","Managing Director & Group CEO","executive","v"],
    ["eaa","Chairman","government","v"],
    ["adcb","Chairman","board","v"],
    ["enec","Chairman","board","v"],
    ["cfg","Chairman","board","v"],
    ], note:"MBZ's key business emissary; bridges sovereign capital, banking, nuclear energy and global sport."},
  {id:"sultan_jaber", n:"Dr. Sultan Ahmed Al Jaber", t:1, p:96, s:"energy", roles:[
    ["fedgov","Minister of Industry & Advanced Technology","political","v"],
    ["adnoc","Managing Director & Group CEO","executive","v"],
    ["masdar","Chairman","board","v"],
    ["xrg","Executive Chairman","board","v"],
    ["mbzuai","Chairman, Board of Trustees","board","ns"],
    ["xrg","CEO","executive","v"],
    ["taqa","Vice Chairman","board","v"],
    ], note:"Runs the hydrocarbon engine and its clean-energy / AI diversification arms; COP28 President."},
  {id:"jassem_zaabi", n:"Jassem Mohamed Bu Ataba Al Zaabi", t:1, p:95, s:"gov", roles:[
    ["dof","Chairman","government","v"],
    ["e_and","Chairman","board","v"],
    ["execcouncil","Member","political","v"],
    ["taqa","Chairman","board","v"],
    ], note:"Controls the emirate's treasury and chairs the telecom giant."},
  {id:"ahmed_jasim_zaabi", n:"Ahmed Jasim Al Zaabi", t:1, p:90, s:"finance", roles:[
    ["added","Chairman","government","v"],
    ["adgm","Chairman","government","v"],
    ["execcouncil","Member","political","v"],
    ], note:"Gatekeeper for economic policy and the financial free zone."},
  {id:"alsuwaidi_adq", n:"Mohamed Hassan Alsuwaidi", t:1, p:92, s:"sovereign", roles:[
    ["fedgov","UAE Minister of Investment","political","v"],
    ["adq","Managing Director & CEO","executive","v"],
    ]},
  {id:"syed_basar", n:"Syed Basar Shueb", t:1, p:85, s:"sovereign", roles:[
    ["ihc","CEO","executive","v"],
    ], note:"Operates Tahnoon's listed conglomerate (IHC), one of the largest listed companies in the Middle East."},
  {id:"faisal_bannai", n:"Faisal Al Bannai", t:1, p:88, s:"tech", roles:[
    ["prescourt","Adviser for Strategic Research & Advanced Technology Affairs","political","v"],
    ["atrc","Secretary-General","government","v"],
    ["edge_grp","Chairman","board","ns"],
    ], note:"Architect of the UAE's sovereign tech & Falcon AI model push; founded EDGE."},
  {id:"peng_xiao", n:"Peng Xiao", t:1, p:88, s:"tech", roles:[
    ["g42","Group CEO","executive","v"],
    ["mgx","Board Member","board","v"],
    ], note:"Runs the G42 AI constellation; the operator of the Tahnoon tech ecosystem."},
  {id:"yousef_otaiba", n:"Yousef Al Otaiba", t:1, p:87, s:"gov", roles:[
    ["mofa","UAE Ambassador to the United States · Minister of State","political","v"],
    ], note:"The external face of Abu Dhabi in Washington; sits at the diplomacy–investment intersection."},
  {id:"anwar_gargash", n:"Dr. Anwar Gargash", t:1, p:82, s:"gov", roles:[
    ["prescourt","Diplomatic Adviser to the President","political","v"],
    ]},
  {id:"shorafa", n:"Mohamed Ali Al Shorafa", t:1, p:87, s:"gov", roles:[
    ["dmt","Chairman","government","v"],
    ["etihad","Chairman, Etihad Aviation Group","board","v"],
    ["sca","Chairman","government","v"],
    ["execcouncil","Member","political","v"],
    ]},
  {id:"mansoori_doh", n:"Mansoor Ibrahim Al Mansoori", t:1, p:85, s:"health", roles:[
    ["doh","Chairman","government","v"],
    ["execcouncil","Member","political","v"],
    ]},
  {id:"sara_musallam", n:"Sara Awadh Musallam", t:1, p:84, s:"education", roles:[
    ["adek","Chairman","government","v"],
    ["fedgov","Minister of State for Early Education","political","v"],
    ["execcouncil","Member","political","v"],
    ]},
  {id:"awaidha_marar", n:"Awaidha Murshed Al Marar", t:1, p:84, s:"utilities", roles:[
    ["doe","Chairman","government","v"],
    ["execcouncil","Member","political","v"],
    ]},
  {id:"kuttab", n:"Ahmed Tamim Hisham Al Kuttab", t:1, p:82, s:"gov", roles:[
    ["dge","Chairman","government","v"],
    ["execcouncil","Member","political","v"],
    ]},
  {id:"falah_ahbabi", n:"Falah Mohammed Al Ahbabi", t:1, p:85, s:"industry", roles:[
    ["adports","Chairman","board","v"],
    ["execcouncil","Member","political","v"],
    ]},
  {id:"mohamed_km", n:"Mohamed Khalifa Al Mubarak", t:1, p:88, s:"consumer_disc", roles:[
    ["dct","Chairman","government","v"],
    ["aldar","Chairman","board","v"],
    ["miral","Chairman","board","v"],
    ["execcouncil","Member","political","v"],
    ], note:"Brother of Khaldoon; controls the culture–tourism–real-estate triangle."},
  {id:"mugheer_khaili", n:"Dr. Mugheer Khamis Al Khaili", t:1, p:80, s:"gov", roles:[
    ["dcd","Chairman","government","v"],
    ["execcouncil","Member","political","v"],
    ]},
  {id:"saif_ghobash", n:"Saif Saeed Ghobash", t:1, p:80, s:"gov", roles:[
    ["execcouncil","Secretary-General","government","ns"],
    ]},
  {id:"ahmed_mazrouei", n:"Dr. Ahmed Mubarak Al Mazrouei", t:1, p:78, s:"gov", roles:[
    ["adafsa","Chairman","government","ns"],
    ["execcouncil","Member","political","v"],
    ]},
  {id:"suhail_mazrouei", n:"Suhail Al Mazrouei", t:1, p:84, s:"energy", roles:[
    ["fedgov","Minister of Energy & Infrastructure","political","v"],
    ]},
  {id:"sarah_amiri", n:"Sarah Al Amiri", t:1, p:82, s:"education", roles:[
    ["fedgov","Minister of Education","political","v"],
    ["spaceagency","Chair","government","v"],
    ]},
  {id:"balama", n:"Khaled Mohamed Balama", t:1, p:83, s:"finance", roles:[
    ["cbuae","Governor","executive","v"],
    ]},
  {id:"noura_kaabi", n:"Noura Al Kaabi", t:1, p:78, s:"gov", roles:[
    ["mofa","Minister of State","political","v"],
    ]},
  {id:"hussain_nowais", n:"Hussain Jasim Al Nowais", t:1, p:80, s:"conglomerate", roles:[
    ["emsteel","Chairman","board","v"],
    ["alnowais","Chairman","board","v"],
    ]},
  {id:"razan", n:"Razan Khalifa Al Mubarak", t:1, p:78, s:"gov", roles:[
    ["ead","Managing Director","executive","v"],
    ], note:"Sister of Khaldoon and Mohamed Khalifa Al Mubarak; also President of IUCN."},
  {id:"tareq_hosani", n:"Tareq Abdul Raheem Al Hosani", t:1, p:76, s:"industry", roles:[
    ["tawazun","Secretary-General","government","v"],
    ]},
  {id:"ghannam", n:"Ghannam Butti Al Mazrouei", t:1, p:74, s:"finance", roles:[
    ["adx","Chairman","board","ns"],
    ]},
  {id:"zaki", n:"Zaki Anwar Nusseibeh", t:1, p:72, s:"education", roles:[
    ["prescourt","Cultural Adviser to the President","political","v"],
    ["uaeu","Chancellor","executive","v"],
    ]},
  {id:"hana", n:"Hana Al Rostamani", t:2, p:82, s:"finance", roles:[
    ["fab","Group CEO","executive","v"],
    ]},
  {id:"alaa", n:"Ala'a Eraiqat", t:2, p:78, s:"finance", roles:[
    ["adcb","Group CEO","executive","v"],
    ]},
  {id:"abdelbary", n:"Mohamed Abdelbary", t:2, p:72, s:"finance", roles:[
    ["adib","Group CEO","executive","ns"],
    ]},
  {id:"jayesh", n:"Jayesh Patel", t:2, p:68, s:"finance", roles:[
    ["wio","CEO","executive","v"],
    ]},
  {id:"adx_ceo", n:"Abdulla Salem Alnuaimi", t:2, p:64, s:"finance", roles:[
    ["adx","Group CEO","executive","ns"],
    ]},
  {id:"waleed", n:"Waleed Al Mokarrab Al Muhairi", t:2, p:82, s:"sovereign", roles:[
    ["mubadala","Deputy Group CEO","executive","v"],
    ["waha","Chairman","board","ns"],
    ]},
  {id:"homaid", n:"Homaid Al Shimmari", t:2, p:76, s:"sovereign", roles:[
    ["mubadala","Deputy Group CEO, Corporate & Human Capital","executive","v"],
    ]},
  {id:"badr_olama", n:"Badr Al-Olama", t:2, p:78, s:"gov", roles:[
    ["adio","Director-General","government","v"],
    ]},
  {id:"ahmed_yahia", n:"Ahmed Yahia Al Idrissi", t:2, p:78, s:"sovereign", roles:[
    ["mgx","CEO","executive","v"],
    ]},
  {id:"khalifa_suwaidi", n:"Khalifa Sultan Al Suwaidi", t:2, p:76, s:"sovereign", roles:[
    ["adq","Chief Investment Officer","executive","v"],
    ["agthia","Chairman","board","v"],
    ["lunate","Managing Partner","executive","ns"],
    ]},
  {id:"samia", n:"Samia Bouazza", t:2, p:70, s:"sovereign", roles:[
    ["multiply","Group CEO","executive","v"],
    ]},
  {id:"alwan", n:"Ahmad Ali Alwan", t:2, p:64, s:"tech", roles:[
    ["hub71","CEO","executive","v"],
    ]},
  {id:"jasim_thabet", n:"Jasim Husain Thabet", t:2, p:84, s:"utilities", roles:[
    ["taqa","Group CEO & Managing Director","executive","v"],
    ]},
  {id:"alshamsi_ewec", n:"Ahmed Ali Alshamsi", t:2, p:78, s:"utilities", roles:[
    ["ewec","CEO","executive","ns"],
    ]},
  {id:"ramahi", n:"Mohamed Jameel Al Ramahi", t:2, p:80, s:"utilities", roles:[
    ["masdar","CEO","executive","v"],
    ]},
  {id:"hammadi_enec", n:"Mohamed Ibrahim Al Hammadi", t:2, p:79, s:"utilities", roles:[
    ["enec","Managing Director & CEO","executive","v"],
    ]},
  {id:"musabbeh", n:"Musabbeh Al Kaabi", t:2, p:78, s:"energy", roles:[
    ["adnoc","Executive Director, Low Carbon Solutions & International Growth","executive","v"],
    ]},
  {id:"abdulmunim", n:"Abdulmunim Saif Al Kindy", t:2, p:70, s:"energy", roles:[
    ["adnoc","Executive Director, Upstream","executive","ns"],
    ]},
  {id:"fatema", n:"Fatema Al Nuaimi", t:2, p:74, s:"energy", roles:[
    ["adnocgas","CEO","executive","ns"],
    ]},
  {id:"seiari", n:"Abdulrahman Al Seiari", t:2, p:70, s:"energy", roles:[
    ["adnocdrill","CEO","executive","ns"],
    ]},
  {id:"masabi", n:"Capt. Abdulkareem Al Masabi", t:2, p:70, s:"energy", roles:[
    ["adnocls","CEO","executive","ns"],
    ]},
  {id:"lamki", n:"Bader Saeed Al Lamki", t:2, p:70, s:"energy", roles:[
    ["adnocdist","CEO","executive","v"],
    ]},
  {id:"hazeem", n:"Hazeem Sultan Al Suwaidi", t:2, p:70, s:"materials", roles:[
    ["borouge","CEO","executive","v"],
    ]},
  {id:"talal_kaissi", n:"Talal Al Kaissi", t:2, p:70, s:"tech", roles:[
    ["core42","CEO (acting)","executive","ns"],
    ]},
  {id:"thomas", n:"Thomas Pramotedham", t:2, p:68, s:"tech", roles:[
    ["presight","CEO","executive","v"],
    ]},
  {id:"karim", n:"Karim Michel Sabbagh", t:2, p:72, s:"tech", roles:[
    ["space42","Managing Director","executive","v"],
    ]},
  {id:"alnaqbi", n:"Hassan Alnaqbi", t:2, p:70, s:"tech", roles:[
    ["khazna","CEO","executive","v"],
    ]},
  {id:"najwa", n:"Dr. Najwa Aaraj", t:2, p:68, s:"tech", roles:[
    ["tii","CEO","executive","v"],
    ]},
  {id:"eric_xing", n:"Prof. Eric Xing", t:2, p:70, s:"education", roles:[
    ["mbzuai","President","executive","v"],
    ]},
  {id:"hamad_marar", n:"Hamad Al Marar", t:2, p:78, s:"industry", roles:[
    ["edge_grp","Managing Director & CEO","executive","v"],
    ]},
  {id:"shaista", n:"Shaista Asif", t:2, p:74, s:"health", roles:[
    ["purehealth","Group CEO","executive","v"],
    ]},
  {id:"hasan_nowais", n:"Hasan Jasem Al Nowais", t:2, p:72, s:"health", roles:[
    ["m42","Managing Director & Group CEO","executive","v"],
    ]},
  {id:"shamsheer", n:"Dr. Shamsheer Vayalil", t:2, p:74, s:"health", roles:[
    ["burjeel","Founder & Chairman","board","v"],
    ]},
  {id:"talal_dhiyebi", n:"Talal Al Dhiyebi", t:2, p:78, s:"realestate", roles:[
    ["aldar","Group CEO","executive","v"],
    ]},
  {id:"bill_oregan", n:"Bill O'Regan", t:2, p:70, s:"realestate", roles:[
    ["modon","Group CEO","executive","v"],
    ]},
  {id:"shamisi_ports", n:"Capt. Mohamed Juma Al Shamisi", t:2, p:80, s:"industry", roles:[
    ["adports","Managing Director & Group CEO","executive","v"],
    ]},
  {id:"neves", n:"Antonoaldo Neves", t:2, p:74, s:"industry", roles:[
    ["etihad","CEO","executive","v"],
    ]},
  {id:"elena", n:"Elena Sorlini", t:2, p:70, s:"industry", roles:[
    ["adairports","Managing Director & CEO","executive","v"],
    ]},
  {id:"shadi", n:"Shadi Malak", t:2, p:72, s:"industry", roles:[
    ["etihadrail","CEO","executive","v"],
    ]},
  {id:"saeed_remeithi", n:"Saeed Ghumran Al Remeithi", t:2, p:68, s:"materials", roles:[
    ["emsteel","Group CEO","executive","v"],
    ]},
  {id:"binkalban", n:"Abdulnasser bin Kalban", t:2, p:72, s:"materials", roles:[
    ["ega","CEO","executive","v"],
    ]},
  {id:"ismail_abdulla", n:"Ismail Ali Abdulla", t:2, p:64, s:"industry", roles:[
    ["strata","CEO","executive","ns"],
    ]},
  {id:"zaghloul", n:"Yasser Zaghloul", t:2, p:68, s:"industry", roles:[
    ["nmdc","Group CEO","executive","v"],
    ]},
  {id:"yusuffali", n:"Yusuff Ali M.A.", t:2, p:78, s:"consumer_stap", roles:[
    ["lulu","Chairman & Managing Director","board","v"],
    ], note:"Abu Dhabi-based retail magnate; one of the most influential expatriate business figures in the Gulf."},
  {id:"miral_zaabi", n:"Mohamed Abdalla Al Zaabi", t:2, p:72, s:"consumer_disc", roles:[
    ["miral","Group CEO","executive","v"],
    ]},
  {id:"humaid_dhaheri", n:"Humaid Matar Al Dhaheri", t:2, p:68, s:"consumer_disc", roles:[
    ["adnec","Managing Director & Group CEO","executive","v"],
    ]},
  {id:"lickrish", n:"John Lickrish", t:2, p:62, s:"comm", roles:[
    ["flash","CEO","executive","v"],
    ]},
  {id:"rani", n:"Rani Raad", t:2, p:68, s:"comm", roles:[
    ["imi","CEO","executive","v"],
    ]},
  {id:"shaikha_dhaheri", n:"Dr. Shaikha Salem Al Dhaheri", t:2, p:74, s:"gov", roles:[
    ["ead","Secretary-General","executive","v"],
    ]},
  {id:"ali_tadweer", n:"Ali Al Dhaheri", t:2, p:64, s:"industry", roles:[
    ["tadweer","Managing Director & CEO","executive","ns"],
    ]},
  {id:"mohamed_butti", n:"Sheikh Mohamed bin Butti Al Hamed", t:2, p:66, s:"conglomerate", roles:[
    ["dasholding","Chairman","board","ns"],
    ]},
  {id:"obaid_aljaber", n:"Obaid Khaleefa Al Jaber", t:2, p:62, s:"conglomerate", roles:[
    ["aljaber","Chairman","board","ns"],
    ]},
  {id:"essam_tamimi", n:"Essam Al Tamimi", t:3, p:60, s:"industry", roles:[
    ["altamimi","Founder & Senior Partner","executive","v"],
    ]},
  {id:"nasser_nowais", n:"Nasser Al Nowais", t:2, p:64, s:"conglomerate", roles:[
    ["rotana","Co-founder & Chairman","board","ns"],
    ]},
  {id:"amr_menhali", n:"Amr Al Menhali", t:2, p:60, s:"finance", roles:[
    ["waha","CEO","executive","ns"],
    ]},
  {id:"hamad_ameri", n:"Eng. Hamad Al Ameri", t:2, p:58, s:"industry", roles:[
    ["trojan","CEO","executive","ns"],
    ]},
  {id:"ahmed_elhoshy", n:"Ahmed El-Hoshy", t:2, p:64, s:"materials", roles:[
    ["fertiglobe","CEO","executive","v"],
    ]},
  {id:"ebrahim_alhajri", n:"Dr. Ebrahim Saeed Al Hajri", t:2, p:62, s:"education", roles:[
    ["khalifa_u","President","executive","v"],
    ], note:"President of Khalifa University since July 2024"},
  {id:"fabio_piano", n:"Fabio Piano", t:2, p:62, s:"education", roles:[
    ["nyuad","Vice Chancellor","executive","v"],
    ], note:"Vice Chancellor of NYU Abu Dhabi since August 2026"},
  {id:"nathalie_martial_braz", n:"Prof. Nathalie Martial-Braz", t:2, p:58, s:"education", roles:[
    ["sorbonne","Chancellor","executive","v"],
    ], note:"Chancellor of Sorbonne University Abu Dhabi"},
  {id:"kevin_hall", n:"Dr. Kevin Hall", t:2, p:60, s:"education", roles:[
    ["zayed_u","President and CEO","executive","v"],
    ], note:"President and CEO of Zayed University since November 2025"},
  {id:"maryam_almheiri", n:"H.E. Maryam Eid AlMheiri", t:1, p:74, s:"comm", roles:[
    ["admo","Chairperson","government","v"],
    ], note:"Chairperson of Abu Dhabi Media Office; former UAE Minister of Climate Change and Environment"},
  {id:"nadim_koteich", n:"Nadim Koteich", t:2, p:58, s:"comm", roles:[
    ["skynewsarabia","General Manager","executive","v"],
    ], note:"General Manager of Sky News Arabia under IMI"},
  {id:"mina_aloraibi", n:"Mina Al-Oraibi", t:2, p:56, s:"comm", roles:[
    ["thenational","Editor-in-Chief","executive","v"],
    ], note:"Editor-in-Chief of The National since 2017"},
  {id:"saeed_alkuwaiti", n:"Saeed Jaber Al Kuwaiti", t:2, p:64, s:"health", roles:[
    ["seha","Group CEO","executive","v"],
    ], note:"Group CEO of SEHA (Abu Dhabi Health Services Company)"},
  {id:"khaled_ateeq_aldhaheri", n:"Khaled Ateeq Al Dhaheri", t:2, p:60, s:"health", roles:[
    ["daman","CEO","executive","v"],
    ], note:"CEO of Daman National Health Insurance Company"},
  {id:"georges_haber", n:"Dr. Georges-Pascal Haber", t:2, p:62, s:"health", roles:[
    ["ccad","CEO","executive","v"],
    ], note:"CEO of Cleveland Clinic Abu Dhabi since June 2024"},
  {id:"khalifa_alblooshi", n:"Dr. Khalifa Murad Al Blooshi", t:2, p:58, s:"industry", roles:[
    ["calidus","Managing Director & CEO","executive","v"],
    ], note:"Managing Director & CEO of Calidus Holding Group"},
  {id:"dhafer_alqasimi", n:"Dhafer Al Qasimi", t:2, p:58, s:"consumer_stap", roles:[
    ["silal","CEO","executive","v"],
    ], note:"CEO of Silal since March 2025"},
  {id:"osman_serageldin", n:"Osman Serageldin", t:2, p:58, s:"consumer_stap", roles:[
    ["aldahra","Interim CEO","executive","v"],
    ], note:"Interim CEO of Al Dahra Holding since August 2026"},
  {id:"khalid_anib", n:"Khalid Anib", t:2, p:58, s:"realestate", roles:[
    ["adnh","CEO","executive","v"],
    ], note:"CEO of Abu Dhabi National Hotels since 2016"},
  {id:"abdulla_alghfeli", n:"Dr. Abdulla Hamad AlGhfeli", t:2, p:58, s:"gov", roles:[
    ["itc","Acting Director-General","government","v"],
    ], note:"Acting Director-General of the Integrated Transport Centre (Abu Dhabi Mobility)"},
  {id:"faraj_binhamoodah", n:"H.E. Faraj Ali Bin Hamoodah Al Dhaheri", t:2, p:56, s:"conglomerate", roles:[
    ["binhamoodah","Chairman","board","v"],
    ], note:"Founder & Chairman of Bin Hamoodah Group"},
  {id:"jawaan_alkhaili", n:"H.E. Jawaan Awaidha Suhail Al-Khaili", t:2, p:60, s:"conglomerate", roles:[
    ["nationalholding","Chairman","board","v"],
    ], note:"Chairman of National Holding"},
  {id:"shamis_aldhaheri", n:"Shamis Al Dhaheri", t:2, p:56, s:"conglomerate", roles:[
    ["alisons","Group Managing Director","executive","v"],
    ], note:"Group Managing Director of Ali & Sons Holding"},
  {id:"fayez_ibbini", n:"Fayez Ibbini", t:2, p:58, s:"tech", roles:[
    ["lst_alphadata","Founder & CEO","executive","v"],
    ], note:"Founder & CEO of Alpha Data"},
  {id:"esteban_gomez", n:"Esteban Gómez Nadal", t:2, p:56, s:"industry", roles:[
    ["lst_e7","CEO","executive","v"],
    ], note:"CEO of E7 Group"},
  {id:"khaled_zaabi_cfo", n:"Khaled Al Zaabi", t:2, p:74, s:"energy", roles:[
    ["adnoc","Group Chief Financial Officer","executive","v"],
    ]},
  {id:"nasser_almuhairi", n:"Nasser Al Muhairi", t:2, p:72, s:"energy", roles:[
    ["adnoc","Acting CEO, Downstream Industry, Marketing & Trading","executive","v"],
    ], note:"Acting CEO of ADNOC's Downstream Industry"},
  {id:"dena_almansoori", n:"Dena Al Mansoori", t:2, p:68, s:"energy", roles:[
    ["adnoc","Group Chief Technology & Innovation Officer","executive","v"],
    ]},
  {id:"hani_barhoush", n:"Hani Barhoush", t:2, p:72, s:"sovereign", roles:[
    ["mubadala","Managing Director & CEO, Mubadala Capital","executive","v"],
    ]},
  {id:"mansour_almulla", n:"Mansour Mohamed AlMulla", t:2, p:72, s:"sovereign", roles:[
    ["adq","Deputy Group Chief Executive Officer","executive","ns"],
    ]},
  {id:"marcos_dequadros", n:"Marcos de Quadros", t:2, p:68, s:"sovereign", roles:[
    ["adq","Group Chief Financial Officer","executive","ns"],
    ]},
  {id:"somar_ajalyaqin", n:"Dr. Mohammed Somar Ajalyaqin", t:2, p:70, s:"sovereign", roles:[
    ["ihc","Vice Chairman","board","ns"],
    ]},
  {id:"alwyn_crasta", n:"Alwyn Crasta", t:2, p:66, s:"sovereign", roles:[
    ["ihc","Group Chief Financial Officer","executive","ns"],
    ]},
  {id:"ali_dalloul", n:"Ali Dalloul", t:2, p:68, s:"tech", roles:[
    ["g42","Group Chief Strategy Officer","executive","v"],
    ], note:"Also CEO of G42's US business"},
  {id:"kiril_evtimov", n:"Kiril Evtimov", t:2, p:68, s:"tech", roles:[
    ["g42","Group Chief Technology Officer","executive","v"],
    ], note:"Also Chairman of G42 Cloud"},
  {id:"adrian_kershaw", n:"Adrian Kershaw", t:2, p:70, s:"utilities", roles:[
    ["taqa","Chief Financial Officer","executive","v"],
    ]},
  {id:"mazin_khan", n:"Mazin Khan", t:2, p:66, s:"utilities", roles:[
    ["masdar","Chief Financial Officer","executive","v"],
    ]},
  {id:"lars_kramer", n:"Lars Kramer", t:2, p:72, s:"finance", roles:[
    ["fab","Group Chief Financial Officer","executive","v"],
    ]},
  {id:"deepak_khullar", n:"Deepak Khullar", t:2, p:70, s:"finance", roles:[
    ["adcb","Group Chief Financial Officer","executive","ns"],
    ]},
  {id:"karim_bennis", n:"Karim Bennis", t:2, p:68, s:"comm", roles:[
    ["e_and","Group Chief Financial Officer","executive","v"],
    ]},
  {id:"saif_dahbashi", n:"Saif Ali Al Dahbashi", t:2, p:64, s:"industry", roles:[
    ["edge_grp","President, Missiles & Weapons Cluster","executive","v"],
    ]},
  {id:"raffael_quintas", n:"Raffael Quintas", t:2, p:66, s:"industry", roles:[
    ["etihad","Chief Financial Officer","executive","v"],
    ]},
  {id:"salmeen_alameri", n:"Salmeen Obaid Alameri", t:2, p:66, s:"consumer_stap", roles:[
    ["agthia","Managing Director & Group CEO","executive","v"],
    ], note:"Managing Director & CEO of Agthia since 2025; previously CEO of Silal."},
  {id:"tahnoun_bin_zayed", n:"Tahnoun bin Zayed Al Nahyan", t:2, p:62, s:"finance", roles:[
    ["fab","Chairman","board","v"],
    ]},
  {id:"sheikh_mohamed_bin", n:"Sheikh Mohamed bin Saif Al Nahyan", t:2, p:62, s:"finance", roles:[
    ["fab","Vice Chairman","board","v"],
    ]},
  {id:"jassem_mohammed_bu", n:"Jassem Mohammed Bu Ataba Al Zaabi", t:2, p:52, s:"finance", roles:[
    ["fab","Board Member","board","v"],
    ]},
  {id:"mariam_bint_mohammed", n:"Mariam bint Mohammed Saeed Hareb Almheiri", t:2, p:52, s:"finance", roles:[
    ["fab","Board Member","board","v"],
    ]},
  {id:"sheikh_ahmed_mohammed", n:"Sheikh Ahmed Mohammed Sultan Aldhaheri", t:2, p:52, s:"finance", roles:[
    ["fab","Board Member","board","v"],
    ]},
  {id:"mohammed_thani_murshed", n:"Mohammed Thani Murshed Al Rumaithi", t:2, p:52, s:"finance", roles:[
    ["fab","Board Member","board","v"],
    ]},
  {id:"mohamed_saif_al", n:"Mohamed Saif Al Suwaidi", t:2, p:52, s:"finance", roles:[
    ["fab","Board Member","board","v"],
    ]},
  {id:"khalifa_ateeq_al", n:"Khalifa Ateeq Al Mazrouei", t:2, p:52, s:"finance", roles:[
    ["fab","Board Member","board","v"],
    ]},
  {id:"futoon_hamdan_al", n:"Futoon Hamdan Al Mazrouei", t:2, p:58, s:"finance", roles:[
    ["fab","Group Head, Personal & Wealth Banking","executive","v"],
    ]},
  {id:"linos_lekkas", n:"Linos Lekkas", t:2, p:58, s:"finance", roles:[
    ["fab","Group Head of Investment Banking & Markets","executive","v"],
    ]},
  {id:"martin_tricaud", n:"Martin Tricaud", t:2, p:58, s:"finance", roles:[
    ["fab","Group Head of Wholesale Banking","executive","v"],
    ]},
  {id:"chris_jaques", n:"Chris Jaques", t:2, p:58, s:"finance", roles:[
    ["fab","Group Chief Risk Officer","executive","v"],
    ]},
  {id:"divyesh_vithlani", n:"Divyesh Vithlani", t:2, p:58, s:"finance", roles:[
    ["fab","Group Chief Technology & Transformation Officer","executive","v"],
    ]},
  {id:"keith_macdonald", n:"Keith Macdonald", t:2, p:58, s:"finance", roles:[
    ["fab","Group Chief Operations Officer","executive","v"],
    ]},
  {id:"noora_al_reyasi", n:"Noora Al Reyasi", t:2, p:58, s:"finance", roles:[
    ["fab","Group Chief Human Resources Officer","executive","v"],
    ]},
  {id:"omar_hafeez", n:"Omar Hafeez", t:2, p:58, s:"finance", roles:[
    ["fab","Group Head of International Banking","executive","v"],
    ]},
  {id:"jawaan_awaidha_suhail", n:"Jawaan Awaidha Suhail Al Khaili", t:2, p:62, s:"finance", roles:[
    ["adib","Chairman","board","v"],
    ]},
  {id:"dr_faisal_sultan", n:"Dr. Faisal Sultan Al Shuaibi", t:2, p:62, s:"finance", roles:[
    ["adib","Vice Chairman","board","v"],
    ]},
  {id:"abdulla_ali_musleh", n:"Abdulla Ali Musleh Al Ahbabi", t:2, p:52, s:"finance", roles:[
    ["adib","Board Member","board","v"],
    ]},
  {id:"abdul_wahab_al", n:"Abdul Wahab Al-Halabi", t:2, p:52, s:"finance", roles:[
    ["adib","Board Member","board","v"],
    ]},
  {id:"khalifa_matar_al", n:"Khalifa Matar Al Mheiri", t:2, p:52, s:"finance", roles:[
    ["adib","Board Member","board","v"],
    ]},
  {id:"maha_mohammad_al", n:"Maha Mohammad Al Qattan", t:2, p:52, s:"finance", roles:[
    ["adib","Board Member","board","v"],
    ]},
  {id:"najib_youssef_fayyad", n:"Najib Youssef Fayyad", t:2, p:52, s:"finance", roles:[
    ["adib","Board Member","board","v"],
    ]},
  {id:"ahsan_akhtar", n:"Ahsan Akhtar", t:2, p:58, s:"finance", roles:[
    ["adib","Group Chief Financial Officer","executive","v"],
    ]},
  {id:"talha_syed_karim", n:"Talha Syed Karim", t:2, p:58, s:"finance", roles:[
    ["adib","Group Chief Risk Officer","executive","v"],
    ]},
  {id:"metha_al_hashmi", n:"Metha Al Hashmi", t:2, p:58, s:"finance", roles:[
    ["adib","Group Chief Credit Officer","executive","v"],
    ]},
  {id:"bushra_alshehhi", n:"Bushra Alshehhi", t:2, p:58, s:"finance", roles:[
    ["adib","Group Chief HR Officer","executive","v"],
    ]},
  {id:"amit_malhotra", n:"Amit Malhotra", t:2, p:58, s:"finance", roles:[
    ["adib","Global Head of Retail Banking","executive","v"],
    ]},
  {id:"hakim_karoui", n:"Hakim Karoui", t:2, p:58, s:"finance", roles:[
    ["adib","Group Head of Wholesale Banking","executive","v"],
    ]},
  {id:"essa_abdulfattah_kazim", n:"Essa Abdulfattah Kazim Al Mulla", t:2, p:62, s:"comm", roles:[
    ["e_and","Vice Chairman","board","v"],
    ]},
  {id:"hesham_abdulla_qassim", n:"Hesham Abdulla Qassim Al Qassim", t:2, p:52, s:"comm", roles:[
    ["e_and","Board Member","board","v"],
    ]},
  {id:"michel_combes", n:"Michel Combes", t:2, p:52, s:"comm", roles:[
    ["e_and","Board Member","board","v"],
    ]},
  {id:"mariam_saeed_ahmed", n:"Mariam Saeed Ahmed Ghobash", t:2, p:52, s:"comm", roles:[
    ["e_and","Board Member","board","v"],
    ]},
  {id:"saleh_abdulla_alabdooli", n:"Saleh Abdulla Alabdooli", t:2, p:52, s:"comm", roles:[
    ["e_and","Board Member","board","v"],
    ]},
  {id:"abdelmonem_bin_eisa", n:"Abdelmonem Bin Eisa Alserkal", t:2, p:52, s:"comm", roles:[
    ["e_and","Board Member","board","v"],
    ]},
  {id:"khalid_abdulwahid_alrustaman", n:"Khalid Abdulwahid Alrustamani", t:2, p:52, s:"comm", roles:[
    ["e_and","Board Member","board","v"],
    ]},
  {id:"otaiba_khalaf_ahmed", n:"Otaiba Khalaf Ahmed Al Otaiba", t:2, p:52, s:"comm", roles:[
    ["e_and","Board Member","board","v"],
    ]},
  {id:"masood_m_sharif", n:"Masood M. Sharif Mahmood", t:2, p:58, s:"comm", roles:[
    ["e_and","Group Chief Executive Officer","executive","v"],
    ]},
  {id:"khalifa_al_shamsi", n:"Khalifa Al Shamsi", t:2, p:60, s:"comm", roles:[
    ["e_and","Managing Director, e& international","executive","v"],
    ]},
  {id:"haitham_abdulrazzak", n:"Haitham Abdulrazzak", t:2, p:58, s:"comm", roles:[
    ["e_and","Group Chief AI & Business Solutions Officer","executive","v"],
    ]},
  {id:"khalid_murshed", n:"Khalid Murshed", t:2, p:58, s:"comm", roles:[
    ["e_and","Group Chief Operations Officer","executive","v"],
    ]},
  {id:"borja_lopez", n:"Borja Lopez", t:2, p:58, s:"comm", roles:[
    ["e_and","Group Chief Strategy Officer","executive","v"],
    ]},
  {id:"obaid_bokisha", n:"Obaid Bokisha", t:2, p:58, s:"comm", roles:[
    ["e_and","Chief of Staff","executive","v"],
    ]},
  {id:"abdulla_humaid_al", n:"Abdulla Humaid Al Jarwan", t:2, p:52, s:"utilities", roles:[
    ["taqa","Board Member","board","ns"],
    ]},
  {id:"kamal_ishaq_almaazmi", n:"Kamal Ishaq Almaazmi", t:2, p:52, s:"utilities", roles:[
    ["taqa","Board Member","board","ns"],
    ]},
  {id:"buthaina_abdulla_almazrouei", n:"Buthaina Abdulla Almazrouei", t:2, p:52, s:"utilities", roles:[
    ["taqa","Board Member","board","ns"],
    ]},
  {id:"muna_ali_al", n:"Muna Ali Al Dhaheri", t:2, p:52, s:"utilities", roles:[
    ["taqa","Board Member","board","ns"],
    ]},
  {id:"hamad_abdulla_al", n:"Hamad Abdulla Al Hammadi", t:2, p:52, s:"utilities", roles:[
    ["taqa","Board Member","board","ns"],
    ]},
  {id:"khaled_mohamed_al", n:"Khaled Mohamed Al Zaabi", t:2, p:52, s:"utilities", roles:[
    ["taqa","Board Member","board","ns"],
    ]},
  {id:"hamsa_parama_shadaksharappa", n:"Hamsa Parama Shadaksharappa", t:2, p:52, s:"utilities", roles:[
    ["taqa","Board Member","board","ns"],
    ]},
  {id:"khaled_h_alkhoori", n:"Khaled H. Alkhoori", t:2, p:52, s:"finance", roles:[
    ["adcb","Board Member","board","v"],
    ]},
  {id:"khalid_deemas_alsuwaidi", n:"Khalid Deemas Alsuwaidi", t:2, p:52, s:"finance", roles:[
    ["adcb","Board Member","board","v"],
    ]},
  {id:"aysha_al_hallami", n:"Aysha Al Hallami", t:2, p:52, s:"finance", roles:[
    ["adcb","Board Member","board","v"],
    ]},
  {id:"carlos_obeid", n:"Carlos Obeid", t:2, p:52, s:"finance", roles:[
    ["adcb","Board Member","board","v"],
    ]},
  {id:"saeed_mohamed_hamad", n:"Saeed Mohamed Hamad Almazrouei", t:2, p:52, s:"finance", roles:[
    ["adcb","Board Member","board","v"],
    ]},
  {id:"sheikh_zayed_bin", n:"Sheikh Zayed Bin Suroor Al Nahyan", t:2, p:52, s:"finance", roles:[
    ["adcb","Board Member","board","v"],
    ]},
  {id:"sheikh_sultan_bin", n:"Sheikh Sultan Bin Suroor Al Dhaheri", t:2, p:52, s:"finance", roles:[
    ["adcb","Board Member","board","v"],
    ]},
  {id:"fatima_al_nuaimi", n:"Fatima Al Nuaimi", t:2, p:52, s:"finance", roles:[
    ["adcb","Board Member","board","v"],
    ]},
  {id:"robbert_muller", n:"Robbert Muller", t:2, p:58, s:"finance", roles:[
    ["adcb","Group Treasurer","executive","v"],
    ]},
  {id:"ludovic_nobili", n:"Ludovic Nobili", t:2, p:58, s:"finance", roles:[
    ["adcb","Group Chief Corporate, Wealth & Investment Banking Officer","executive","v"],
    ]},
  {id:"mohammed_al_jayyash", n:"Mohammed Al Jayyash", t:2, p:58, s:"finance", roles:[
    ["adcb","Group Chief Operating Officer","executive","v"],
    ]},
  {id:"deepak_rochlani", n:"Deepak Rochlani", t:2, p:58, s:"finance", roles:[
    ["adcb","Group Chief Retail Banking Officer","executive","v"],
    ]},
  {id:"abdulla_abdul_aziz", n:"Abdulla Abdul Aziz AlShamsi", t:2, p:58, s:"finance", roles:[
    ["adcb","Group Chief Business Officer","executive","v"],
    ]},
  {id:"reem_albanna", n:"Reem AlBanna", t:2, p:58, s:"finance", roles:[
    ["adcb","Group Chief Risk Officer","executive","v"],
    ]},
  {id:"sofia_abdellatif_lasky", n:"Sofia Abdellatif Lasky", t:2, p:52, s:"realestate", roles:[
    ["aldar","Board Member","board","v"],
    ]},
  {id:"dr_bakheet_saeed", n:"Dr. Bakheet Saeed Al Katheeri", t:2, p:52, s:"realestate", roles:[
    ["aldar","Board Member","board","v"],
    ]},
  {id:"eng_hamad_salem", n:"Eng. Hamad Salem Mohamed Al Ameri", t:2, p:52, s:"realestate", roles:[
    ["aldar","Board Member","board","ns"],
    ]},
  {id:"faisal_falaknaz", n:"Faisal Falaknaz", t:2, p:58, s:"realestate", roles:[
    ["aldar","Group Chief Financial & Sustainability Officer","executive","v"],
    ]},
  {id:"bayan_al_hosani", n:"Bayan Al Hosani", t:2, p:58, s:"realestate", roles:[
    ["aldar","Chief People & Communications Officer","executive","v"],
    ]},
  {id:"jonathan_emery", n:"Jonathan Emery", t:2, p:60, s:"realestate", roles:[
    ["aldar","CEO, Aldar Development","executive","ns"],
    ]},
  {id:"hatem", n:"Hatem Dowidar", t:2, p:56, s:"comm", roles:[
    ["e_and","Group Chief Executive Officer (2020–2025)","executive","v","former:until 2025"],
    ], note:"Group CEO of e& 2020–2025; led the Etisalat-to-e& rebrand and Vodafone stake build. Succeeded by Masood M. Sharif Mahmood."},
  {id:"alan_smith", n:"Alan Smith", t:3, p:46, s:"consumer_stap", roles:[
    ["agthia","Group Chief Executive Officer (2020–2025)","executive","v","former:until 2025"],
    ], note:"Group CEO of Agthia until 2025; drove its M&A-led expansion. Succeeded by Salmeen Al Ameri."},
];

const OWNERSHIP = [
  ["execcouncil","adgov","governs under","v"],
  ["scfea","adgov","reports to","v"],
  ["eaa","adgov","reports to","v"],
  ["dof","execcouncil","","v"],
  ["added","execcouncil","","v"],
  ["doe","execcouncil","","v"],
  ["doh","execcouncil","","v"],
  ["dmt","execcouncil","","v"],
  ["dge","execcouncil","","v"],
  ["adek","execcouncil","","v"],
  ["dct","execcouncil","","v"],
  ["dcd","execcouncil","","v"],
  ["ead","execcouncil","","v"],
  ["adafsa","execcouncil","","v"],
  ["adio","added","reports to","ns"],
  ["admo","adgov","","v"],
  ["itc","dmt","","v"],
  ["mofa","fedgov","","v"],
  ["cbuae","fedgov","","v"],
  ["sca","fedgov","","v"],
  ["spaceagency","fedgov","","v"],
  ["eia","fedgov","","v"],
  ["tawazun","adgov","","v"],
  ["atrc","adgov","","v"],
  ["tii","atrc","","v"],
  ["adia","adgov","","v"],
  ["mubadala","adgov","","v"],
  ["adq","adgov","","v"],
  ["adnoc","scfea","state owner","v"],
  ["xrg","adnoc","","v"],
  ["adnocgas","adnoc","","v"],
  ["adnocdrill","adnoc","","v"],
  ["adnocls","adnoc","","v"],
  ["adnocdist","adnoc","","v"],
  ["borouge","adnoc","","v"],
  ["fertiglobe","adnoc","","v"],
  ["masdar","adnoc","co-shareholder","v"],
  ["masdar","taqa","co-shareholder","v"],
  ["masdar","mubadala","co-shareholder","v"],
  ["taqa","adq","majority","v"],
  ["ewec","adq","","v"],
  ["enec","adgov","state owner","ns"],
  ["fab","mubadala","anchor shareholder","v"],
  ["adcb","mubadala","majority","v"],
  ["wio","adq","lead shareholder","v"],
  ["adx","adq","","v"],
  ["adgm","adgov","","v"],
  ["ihc","royalgroup","affiliated","ns"],
  ["chimera","royalgroup","","v"],
  ["lunate","chimera","","v"],
  ["twopointzero","ihc","","v"],
  ["alphadhabi","ihc","","v"],
  ["multiply","ihc","","v"],
  ["aldar","alphadhabi","major shareholder","v"],
  ["aldar","mubadala","major shareholder","v"],
  ["modon","adq","anchor shareholder","ns"],
  ["nmdc","alphadhabi","major shareholder","v"],
  ["g42","royalgroup","affiliated","ns"],
  ["core42","g42","","v"],
  ["presight","g42","","v"],
  ["khazna","g42","","v"],
  ["space42","g42","co-shareholder","v"],
  ["space42","mubadala","co-shareholder","v"],
  ["mgx","mubadala","founding partner","v"],
  ["mgx","g42","founding partner","v"],
  ["e_and","eia","majority (federal)","v"],
  ["edge_grp","adgov","state owner","v"],
  ["purehealth","ihc","major shareholder","v"],
  ["purehealth","adq","major shareholder","v"],
  ["seha","purehealth","","v"],
  ["daman","purehealth","","v"],
  ["m42","mubadala","JV partner","v"],
  ["m42","g42","JV partner","v"],
  ["ccad","m42","","v"],
  ["adports","adq","majority","v"],
  ["etihad","adq","","v"],
  ["adairports","adq","","v"],
  ["etihadrail","adgov","state owner","ns"],
  ["ega","mubadala","50% shareholder","v"],
  ["emsteel","adq","majority (SENAAT)","v"],
  ["strata","mubadala","","v"],
  ["agthia","adq","majority","v"],
  ["silal","adq","","v"],
  ["aldahra","adq","strategic stake","ns"],
  ["tadweer","adq","","v"],
  ["hub71","mubadala","founded by","v"],
  ["miral","adgov","state owner","v"],
  ["adnec","adq","","v"],
  ["louvre","dct","","v"],
  ["skynewsarabia","imi","","v"],
  ["thenational","imi","","v"],
  ["g42","microsoft","strategic investor (US$1.5B)","v"],
  ["openai","g42","Stargate UAE partnership","v"],
  ["openai","mgx","investor & Stargate partner","v"],
  ["g42","nvidia","AI compute partnership","v"],
  ["cerebras","g42","anchor customer & investor","v"],
  ["huawei","e_and","technology partner","ns"],
  ["totalenergies","adnoc","concession partner","v"],
  ["bp","adnoc","concession partner · Arcius Energy JV (XRG)","v"],
  ["shell","adnoc","concession partner","v"],
  ["exxonmobil","adnoc","Upper Zakum partner","v"],
  ["eni","adnoc","concession partner","v"],
  ["oxy","adnoc","concession partner","v"],
  ["inpex","adnoc","concession partner","v"],
  ["cnpc","adnoc","concession partner","v"],
  ["omv","borouge","Borouge Group co-shareholder","v"],
  ["kepco","enec","Barakah JV partner","v"],
  ["blackrock","mgx","AI Infrastructure Partnership (AIP)","v"],
  ["nvidia","mgx","AI Infrastructure Partnership (AIP)","v"],
  ["goldman","adgm","regional office (ADGM)","ns"],
  ["moelis","adgm","regional office (ADGM)","ns"],
  ["rothschildco","adgm","regional office (ADGM)","ns"],
  ["mckinsey","added","government & SOE advisory ecosystem","ns"],
  ["bcg","added","government & SOE advisory ecosystem","ns"],
  ["pwc","added","audit & advisory ecosystem","ns"],
  ["ey","added","audit & advisory ecosystem","ns"],
  ["kpmg","added","audit & advisory ecosystem","ns"],
  ["deloitte","added","audit & advisory ecosystem","ns"],
  ["accenture","dge","digital government delivery","ns"],
  ["altamimi","adgm","ADGM & Abu Dhabi practice","ns"],
  ["cliffordchance","adgm","ADGM office","ns"],
  ["waha","mubadala","strategic shareholder","ns"],
  ["adnic","mubadala","major shareholder","ns"],
  ["trojan","alphadhabi","subsidiary","v"],
  ["rotana","alnowais","co-founded (Al Nowais)","ns"],
  ["raytheon_em","tawazun","defense partnerships","ns"],
  ["lst_eand","adx","listed on ADX","ns"],
  ["lst_ords","adx","listed on ADX","ns"],
  ["lst_adports","adx","listed on ADX","ns"],
  ["lst_mbme","adx","listed on ADX","ns"],
  ["lst_purehealth","adx","listed on ADX","ns"],
  ["lst_2pointzero","adx","listed on ADX","ns"],
  ["lst_agility","adx","listed on ADX","ns"],
  ["lst_apex","adx","listed on ADX","ns"],
  ["lst_sib","adx","listed on ADX","ns"],
  ["lst_inb","adx","listed on ADX","ns"],
  ["lst_alefedt","adx","listed on ADX","ns"],
  ["lst_oras","adx","listed on ADX","ns"],
  ["lst_dana","adx","listed on ADX","ns"],
  ["lst_adaviation","adx","listed on ADX","ns"],
  ["lst_bos","adx","listed on ADX","ns"],
  ["lst_uab","adx","listed on ADX","ns"],
  ["lst_emobility","adx","listed on ADX","ns"],
  ["lst_icap","adx","listed on ADX","ns"],
  ["lst_phx","adx","listed on ADX","ns"],
  ["lst_gih","adx","listed on ADX","ns"],
  ["lst_rakprop","adx","listed on ADX","ns"],
  ["lst_saga","adx","listed on ADX","ns"],
  ["lst_anan","adx","listed on ADX","ns"],
  ["lst_esg","adx","listed on ADX","ns"],
  ["lst_asm","adx","listed on ADX","ns"],
  ["lst_ghitha","adx","listed on ADX","ns"],
  ["lst_rakcec","adx","listed on ADX","ns"],
  ["lst_mair","adx","listed on ADX","ns"],
  ["lst_invictus","adx","listed on ADX","ns"],
  ["lst_e7","adx","listed on ADX","ns"],
  ["lst_eshraq","adx","listed on ADX","ns"],
  ["lst_adsb","adx","listed on ADX","ns"],
  ["lst_gmpc","adx","listed on ADX","ns"],
  ["lst_alphadata","adx","listed on ADX","ns"],
  ["lst_eic","adx","listed on ADX","ns"],
  ["lst_palms","adx","listed on ADX","ns"],
  ["lst_julphar","adx","listed on ADX","ns"],
  ["lst_dhafra","adx","listed on ADX","ns"],
  ["lst_scidc","adx","listed on ADX","ns"],
  ["lst_manazel","adx","listed on ADX","ns"],
  ["lst_sudatel","adx","listed on ADX","ns"],
  ["lst_qic","adx","listed on ADX","ns"],
  ["lst_easylease","adx","listed on ADX","ns"],
  ["lst_fh","adx","listed on ADX","ns"],
  ["lst_rakwct","adx","listed on ADX","ns"],
  ["lst_kico","adx","listed on ADX","ns"],
  ["lst_alain","adx","listed on ADX","ns"],
  ["lst_gcem","adx","listed on ADX","ns"],
  ["lst_fbi","adx","listed on ADX","ns"],
  ["lst_rpm","adx","listed on ADX","ns"],
  ["lst_sawaeed","adx","listed on ADX","ns"],
  ["lst_union","adx","listed on ADX","ns"],
  ["lst_hh","adx","listed on ADX","ns"],
  ["lst_fidelityunited","adx","listed on ADX","ns"],
  ["lst_hayah","adx","listed on ADX","ns"],
  ["lst_sico","adx","listed on ADX","ns"],
  ["lst_rapco","adx","listed on ADX","ns"],
  ["lst_aram","adx","listed on ADX","ns"],
  ["lst_fci","adx","listed on ADX","ns"],
  ["lst_oeihc","adx","listed on ADX","ns"],
  ["lst_ih","adx","listed on ADX","ns"],
  ["lst_methaq","adx","listed on ADX","ns"],
];

const FAMILY = [
  ["mbz","tahnoun","brothers"],
  ["mbz","mansour","brothers"],
  ["mbz","hazza","brothers"],
  ["mbz","abdullah_bz","brothers"],
  ["mbz","saif_bz","brothers"],
  ["mbz","hamdan_bz","brothers"],
  ["mbz","hamed_bz","brothers"],
  ["mbz","khaled","father–son"],
  ["mbz","theyab","father–son"],
  ["khaled","theyab","brothers"],
  ["khaldoon","mohamed_km","brothers"],
  ["khaldoon","razan","siblings"],
  ["mohamed_km","razan","siblings"],
  ["hussain_nowais","hasan_nowais","family (Al Nowais)"],
  ["hussain_nowais","nasser_nowais","family (Al Nowais)"],
];

const AKA = {
  mbz:["Mohamed bin Zayed","Mohammed bin Zayed","MBZ"],
  khaled:["Khaled bin Mohamed bin Zayed","Khaled bin Mohamed"],
  tahnoun:["Tahnoun bin Zayed","Tahnoon bin Zayed","Sheikh Tahnoon","Sheikh Tahnoun"],
  mansour:["Mansour bin Zayed"],
  abdullah_bz:["Abdullah bin Zayed"],
  sultan_jaber:["Sultan Al Jaber"],
  khaldoon:["Khaldoon Al Mubarak"],
  mohamed_km:["Mohamed Khalifa Al Mubarak"],
  jassem_zaabi:["Jassem Al Zaabi"],
  alsuwaidi_adq:["Mohamed Al Suwaidi","Mohamed Hassan Al Suwaidi"],
  adnoc:["Abu Dhabi National Oil Company"],
  e_and:["Etisalat"],
  adq:["Abu Dhabi Developmental Holding"],
  ihc:["International Holding Co"],
  adia:["Abu Dhabi Investment Authority"],
  ega:["Emirates Global Aluminium"],
  enec:["Emirates Nuclear Energy"],
};
